//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.07 at 01:34:11 PM CEST
//


package nl.vpro.domain.media.nebo.webonly.v1_4;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;

import org.apache.commons.lang3.StringUtils;

import nl.vpro.domain.media.Program;
import nl.vpro.domain.media.support.Image;


/**
 * <p>Java class for iconType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="iconType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="file" type="{}iconFileResType"/>
 *         &lt;element name="titel" type="{}stringResType255"/>
 *         &lt;element name="omschrijving" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="keywords" type="{}stringResType255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(name = "iconType", propOrder = {
        "file",
        "titel",
        "omschrijving",
        "keywords"
        })
public class IconType {

    private String file;
    private String title;
    private String omschrijving;
    private String keywords;

    IconType() {
    }

    public IconType(Program program) {
        Image image = WebonlyType.getFromCollection(program.getImages());
        if (StringUtils.isEmpty(image.getTitle())) {
            this.title = program.getMainTitle();
        } else {
            this.title = image.getTitle();
        }
        final String uri = image.getImageUri();
        this.file = uri.substring(uri.lastIndexOf(':') + 1) + ".jpg";
        this.omschrijving = image.getDescription();
        this.keywords = this.title;
    }

    @XmlElement(required = true)
    public String getFile() {
        return this.file;
    }

    public void setFile(String value) {
        this.file = value;
    }

    @XmlElement(required = true)
    public String getTitel() {
        return this.title;
    }
    public void setTitel(String value) {
        this.title = value;
    }

    public String getOmschrijving() {
        return this.omschrijving;
    }

    public void setOmschrijving(String value) {
        this.omschrijving = value;
    }
    public String getKeywords() {
        return keywords;
    }
    public void setKeywords(String value) {
        this.keywords = value;
    }
}

