//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.07 at 01:34:11 PM CEST
//


package nl.vpro.domain.media.nebo.webonly.v1_4;

import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Locale;

import jakarta.xml.bind.annotation.*;
import jakarta.xml.datatype.DatatypeConfigurationException;
import jakarta.xml.datatype.DatatypeFactory;
import jakarta.xml.datatype.XMLGregorianCalendar;

import nl.vpro.domain.media.Program;


/**
 * <p>Java class for rootType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="rootType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="webonly" type="{}webonlyType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="webonly" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="notificatie" type="{}emailResType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 * @author Michiel Meeuwissen (renamed and constructors)
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "rootType", propOrder = {
        "webonly"
        })
@XmlRootElement(name = "nebo_xml")
public class NeboXmlWebOnly {

    @XmlElement(required = true)
    protected WebonlyType webonly;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;
    @XmlAttribute(name = "notificatie")
    protected String notificatie;


    public NeboXmlWebOnly(Program program, String group) throws DatatypeConfigurationException {
        type = "webonly";
        GregorianCalendar cal = new GregorianCalendar(new Locale("nl", "NL"));
        cal.setGregorianChange(new Date());
        timestamp = DatatypeFactory.newInstance().newXMLGregorianCalendar(cal);
        webonly = new WebonlyType(program, group);
    }

    public NeboXmlWebOnly() throws DatatypeConfigurationException {
        this(new Program(), null);
    }

    public WebonlyType getWebonly() {
        return webonly;
    }
    public void setWebonly(WebonlyType value) {
        this.webonly = value;
    }
    public String getType() {
        if (type == null) {
            return "webonly";
        } else {
            return type;
        }
    }
    public void setType(String value) {
        this.type = value;
    }

    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    public String getNotificatie() {
        return notificatie;
    }

    public void setNotificatie(String value) {
        this.notificatie = value;
    }

    public Program getProgram() {
        return webonly.getProgram();
    }
}
