//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.07 at 01:34:11 PM CEST
//


package nl.vpro.domain.media.nebo.webonly.v1_4;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;

import nl.vpro.domain.user.Broadcaster;


/**
 * <p>Java class for omroepType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="omroepType">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>stringResType100">
 *       &lt;attribute name="hoofdomroep" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "omroepType", propOrder = {
        "value"
        })
public class OmroepType {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "hoofdomroep", required = true)
    protected boolean hoofdomroep;

    public OmroepType(Broadcaster broadcaster, boolean main) {
        this.value = broadcaster.getDisplayName();
        this.hoofdomroep = main;
    }

    public OmroepType() {


    }

    /**
     * Gets the value of the value property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Gets the value of the hoofdomroep property.
     *
     */
    public boolean isHoofdomroep() {
        return hoofdomroep;
    }

    /**
     * Sets the value of the hoofdomroep property.
     *
     */
    public void setHoofdomroep(boolean value) {
        this.hoofdomroep = value;
    }

}
