//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.07 at 01:34:11 PM CEST
//


package nl.vpro.domain.media.nebo.webonly.v1_4;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for referentieResType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="referentieResType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="prid"/>
 *     &lt;enumeration value="srid"/>
 *     &lt;enumeration value="webprid"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "referentieResType")
@XmlEnum
public enum ReferentieResType {

    @XmlEnumValue("prid")
    PRID("prid"),
    @XmlEnumValue("srid")
    SRID("srid"),
    @XmlEnumValue("webprid")
    WEBPRID("webprid");
    private final String value;

    ReferentieResType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReferentieResType fromValue(String v) {
        for (ReferentieResType c: ReferentieResType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
