//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.11.02 at 10:24:46 AM CET
//


package nl.vpro.domain.npo.notify.nep;

import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for notifyType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="notifyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ONLINE"/>
 *     &lt;enumeration value="OFFLINE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "notifyType")
@XmlEnum
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
public enum NotifyType {


    /**
     * The notification is meant to indicate that the streams are now online
     *
     */
    ONLINE,

    /**
     * The notification is meant to indicate that the streams are now offline
     *
     */
    OFFLINE;

    public String value() {
        return name();
    }

    public static NotifyType fromValue(String v) {
        return valueOf(v);
    }

}
