//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.11.02 at 10:24:46 AM CET
//


package nl.vpro.domain.npo.notify.nep;

import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.datatype.Duration;
import jakarta.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="mid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="type" use="required" type="{urn:vpro:media:notify:2017}notifyType" />
 *       &lt;attribute name="drm" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="duration" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="offline" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "notify")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Notify {

    @XmlAttribute(name = "timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected XMLGregorianCalendar timestamp;
    @XmlAttribute(name = "mid", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String mid;
    @XmlAttribute(name = "type", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected NotifyType type;
    @XmlAttribute(name = "drm")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Boolean drm;
    @XmlAttribute(name = "duration")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Duration duration;
    @XmlAttribute(name = "offline")
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected XMLGregorianCalendar offline;

    /**
     * Gets the value of the timestamp property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the mid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getMid() {
        return mid;
    }

    /**
     * Sets the value of the mid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setMid(String value) {
        this.mid = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link NotifyType }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public NotifyType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link NotifyType }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setType(NotifyType value) {
        this.type = value;
    }

    /**
     * Gets the value of the drm property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Boolean isDrm() {
        return drm;
    }

    /**
     * Sets the value of the drm property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDrm(Boolean value) {
        this.drm = value;
    }

    /**
     * Gets the value of the duration property.
     *
     * @return
     *     possible object is
     *     {@link Duration }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     *
     * @param value
     *     allowed object is
     *     {@link Duration }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the offline property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public XMLGregorianCalendar getOffline() {
        return offline;
    }

    /**
     * Sets the value of the offline property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-11-02T10:24:46+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setOffline(XMLGregorianCalendar value) {
        this.offline = value;
    }

}
