---
codecov:
  branch: main
  disable_default_path_fixes: false

  notify:
    require_ci_to_pass: false

coverage:
  precision: 2
  round: down
  range: "10...90"

  status:
    project: true
    patch: true
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "header, diff"
  behavior: default
  require_changes: false
