//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.03.30 at 03:14:06 PM CEST
//


package nl.vpro.domain.media;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

@XmlEnum
@XmlType(name = "avTypeEnum")
public enum AVType {

    AUDIO {
        @Override
        public String toString() {
            return "Audio";
        }
    },
    VIDEO {
        @Override
        public String toString() {
            return "Video";
        }
    },
    MIXED {
        @Override
        public String toString() {
            return "Afwisselend";
        }
    }
}
