/*
 * Copyright (C) 2010 All rights reserved
 * VPRO The Netherlands
 */
package nl.vpro.domain.media;

import nl.vpro.domain.*;

/**
 * Object that are identifiable with their 'MID' (or 'media id'). These ids are generated by METIS.
 *
 * This currently also extends {@link Identifiable} because all objects also have an id that is generated by the poms backend itself.
 * @since 5.11
 */
public interface MidIdentifiable extends Identifiable<Long> {

    String getMid();

    MediaType getMediaType();


}
