/*
 * Copyright (C) 2010 Licensed under the Apache License, Version 2.0
 * VPRO The Netherlands
 */
package nl.vpro.domain.media;

import nl.vpro.domain.Identifiable;

/**
 * Object that are identifiable with their 'MID' (or 'media id'). These ids are generated by METIS.
 * <p>
 * This currently also extends {@link Identifiable} because all objects also have an id that is generated by the poms backend itself.
 * @since 5.11
 */
public interface MidIdentifiable extends Identifiable<Long> {

    String getMid();

    MediaType getMediaType();


    default String getCorrelationId() {
        return getCorrelation().id;
    }

    /**

     */
    default MediaIdentifiable.Correlation getCorrelation () {
        String mid = getMid();
        if (mid != null) {
            return MediaIdentifiable.Correlation.mid(mid);
        }
        return new MediaIdentifiable.Correlation(String.valueOf(hashCode()), MediaIdentifiable.Correlation.Type.HASH);
    }


}
