= Json Schema and Validation
:toc:

== Intro

Trying this out 'vrije ruimte' of 2022-06-13. Relates to http://json-schema.org/

https://json-schema.org/implementations.html

Goal is to add links to json schema's in https://rs.poms.omroep.nl/v1/schema/

== Schema generation

Our domain objects are entirely specified in java. So you would like to _generate_ the schema from those.

This can be done using https://github.com/FasterXML/jackson-module-jsonSchema

[source, xml]
----
    <dependency>
      <groupId>com.fasterxml.jackson.module</groupId>
      <artifactId>jackson-module-jsonSchema</artifactId>
      <exclusions>
        <exclusion>
          <!-- we use jakarta.validation -->
          <groupId>javax.validation</groupId>
          <artifactId>validation-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
----

- It seems to generate quite old fashioned version 3 of json-schema
- There is also a project for V4: https://github.com/mbknor/mbknor-jackson-jsonSchema
- Both don't seem to be maintained actively
- Even V4 is a bit disappointing, as the latest version is V7, or Draft 2020-12 ?

== Schema validation.

I first considered

[source, xml]
----
    <dependency>
      <groupId>com.networknt</groupId>
      <artifactId>json-schema-validator</artifactId>
      <version>1.0.70</version>
    </dependency>

----
Sadly, only >= v4?

[source, xml]
----
  <dependency>
      <groupId>com.github.java-json-tools</groupId>
      <artifactId>json-schema-validator</artifactId>
      <version>2.2.14</version>
    </dependency>
----
May be interesting for V3 validation?


== Provisional conclusion.

I didn't have much time today. But provisionally I'd say:

- Generating V3 schema can be easily added. (though I don't see how to group those per namespace, probably easiest to just add a link per relevant root element)
- But I don't know yet how to also add _validation_ which would make it more useful, we could offer server side validation of json, which would help developers trying to intergrate with our API's.

=== TODO

- At least not in java, may be try it out in python or javascript or so.
- Generate links anyway. Some work is done already in this branch.


