= poms-shared

image:https://github.com/npo-poms/poms-shared/workflows/build/badge.svg?[Build Status,link=https://github.com/npo-poms/poms-shared/actions?query=workflow%3Abuild]
//image:https://travis-ci.com/npo-poms/poms-shared.svg?[Build Status,link=https://travis-ci.com/npo-poms/poms-shared]
image:https://img.shields.io/maven-central/v/nl.vpro.poms/poms-shared.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:%22nl.vpro.poms%22%20OR%20g:%22nl.vpro.media%22%20OR%20g:%22nl.vpro.api%22]
//image:https://codecov.io/gh/npo-poms/poms-shared/branch/main/graph/badge.svg[codecov,link=https://codecov.io/gh/npo-poms/poms-shared]
image:http://www.javadoc.io/badge/nl.vpro.media/media-domain.svg?color=blue[javadoc,link=http://www.javadoc.io/doc/nl.vpro.media/media-domain]
image:https://img.shields.io/nexus/s/https/oss.sonatype.org/nl.vpro.poms/poms-shared-parent.svg[snapshots,link=https://oss.sonatype.org/content/repositories/snapshots/nl/vpro/poms/poms-shared/]

The java domain classes used by NPO Frontend API, POMS Backend and other POMS projects.

These are also used by the API clients.

See also https://github.com/npo-poms/poms-parent[poms parent]


== build

This is automatically build on github.


Basically it's just
[source, bash]
====
 michiel@mitulo:~/github/npo-poms/poms-shared$ mvn
 [INFO] Scanning for projects...
 [INFO] ------------------------------------------------------------------------
 [INFO] Reactor Build Order:
 [INFO]
 [INFO] poms shared                                                        [pom]
 [INFO] poms-shared-domain                                                 [jar]
 [INFO] poms-shared                                                        [jar]
 [INFO] user-domain                                                        [jar]
 ...
====

The github build can be done locally with 'https://github.com/nektos/act[act]'. Create a file '${USER.HOME}/.secrets' (a propertyfile with the secrets of this project) and then:

[source, bash]
====
 michiel@mitulo:~/github/npo-poms/poms-shared$ act
 [build/build] ðŸš€  Start image=nektos/act-environments-ubuntu:18.04
 [build/build]   ðŸ³  docker run image=nektos/act-environments-ubuntu:18.04 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
 [build/build]   ðŸ³  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root
 ...
====

== Compatibility


|===
|poms shared  | java | remarks
| 4.x | java 8 |
|5.x | java 8 |
|6.x  | java 8 | openshift
|7.x  | java 11 |"
|>= 7.7  | java 17 | august 2023
| 7.11-SNAPSHOT branch | latest javax branch. Minor releases can be made from this. >= 7.12 must be branched from this, not from main | february 2024
| 8.x?| javax - > jakarta  | february 2024
| 8.1?| hibernate 6  | may 2024, hibernate is only an optional dependency (only the annotations are used in this project)
| 9.x? | java 21 | early 2024
|===


== Maven versioning

We are in a kind of hybrid situation
For `main` we use link:https://maven.apache.org/maven-ci-friendly.html['CI friendly' versioning] (using `revision` and `changelist` properties).

For release branches this is overridden by the release:branch plugin

This means that open pull requests (on `main`) will result in artifacts on sonatype snapshots that have the name of the branch in their version.  They can be used in associated merge requests in other projects (likely one of the poms projects in the VPRO gitlab repository)


== Releasing

Make sure SNAPSHOT are resolved. Furthermore, it's similar to as described in https://github.com/npo-poms/poms-parent/blob/main/RELEASE.adoc:[poms parent].

See https://github.com/npo-poms/poms-parent/actions[actions]
