//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.07 at 01:34:11 PM CEST
//


package nl.vpro.domain.media.nebo.shared;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;

import nl.vpro.domain.media.AVFileFormat;


/**
 * <p>Java class for formatResType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="formatResType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="wmv"/>
 *     &lt;enumeration value="mov"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "formatResType")
@XmlEnum
public enum FormatResType {

    @XmlEnumValue("wmv")
    WMV("wmv", AVFileFormat.WMP),
    @XmlEnumValue("mov")
    MOV("mov", AVFileFormat.MP4);
    private final String value;

    private final AVFileFormat avFileFormat;

    FormatResType(String v, AVFileFormat avFileFormat) {
        value = v;
        this.avFileFormat = avFileFormat;
    }

    public String value() {
        return value;
    }

    public static FormatResType fromValue(String v) {
        for (FormatResType c: FormatResType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
    public AVFileFormat getAVFileFormat() {
        return avFileFormat;
    }

}
