= NEP api clients
:toc:

As used by POMS.

NEP makes several API's available, which we make use of in POMS. It's a bit messy, we don't quite know which people are responsible for which API's nor how they relate to one another, and don't know of any publicly available documentation.

== REST APIs

=== NEPGatekeeperService
Intake for transcoding jobs. Poll the 'getTranscodeStatuses' endpoints./. Or it is called by via the 'postkantoor', as a streaming status call.

`nep.gatekeeper-api.baseUrl=https://npo-webonly-gatekeeper.nepworldwide.nl`

http://npo-gatekeeper-prd.cdn2.usvc.nepworldwide.nl/swagger-ui.html

http://npo-gatekeeper-prd.cdn2.usvc.nepworldwide.nl/v2/api-docs

Only for landscape video.

=== NEPSourceServiceIngestService


WIP

Absurdly, if you need to upload a video with a portrait aspect ratio, you need to use this (new) API. We were not provided much documentation, and it is not clear how it relates to the NEPGatekeeperService. I presume it is a rewrite.

See https://publiekeomroep.atlassian.net/browse/P0MS-251

It is currently unknown how to monitor this.


=== NEPItemizeService
Intake for 'itemize' and 'grab screen'.


|===
|env | `nep.itemizer-api.baseUrl`=

|prod | `https://itemizer-npocdn-prd.nepworldwide.nl/v1`
|new prod | `https://itemizer-gateway.nepworldwide.nl/v1/` ??
|staging | `https://itemizer-npocdn-stg.nepworldwide.nl/v1`
|===


=== NEPPlayerTokenService

widevine token, playready tokens

`nep.tokengenerator-api.baseUrl=https://drm-token-provider.nepworldwide.nl/authenticate/`


=== NEPSAMService

'Stream Access Management' API

`nep.sam-api.baseUrl=https://api.samgcloud.nepworldwide.nl/`

== FTP Services

There are tree relevant FTP servers of which we wrap the relevant function into the following interfaces

=== NEPUploadService
If you want to upload something for transcoding upload it to one of the following FTP servers.

`nep.gatekeeper-upload.host=ftp.nepworldwide.nl` (for landscape video)


`nep.sourcing-service-upload.host=ftp1.cdn1.usvc.nepworldwide.nl ` (for portrait video)

=== NEPDownloadService
If you want to download transcoded item, or itemized item. (iirc)

`nep.itemizer-download.host=sftp-itemizer.nepworldwide.nl`
`
