//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.21 at 10:52:28 AM CEST
//


package nl.vpro.domain.npo.projectm.metadata.v2_1;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;

import java.math.BigInteger;

import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the nl.vpro.domain.npo.projectm.metadata.v21 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Bron_QNAME = new QName("", "bron");
    private final static QName _Inh3_QNAME = new QName("", "inh3");
    private final static QName _GidsTekst_QNAME = new QName("", "gids_tekst");
    private final static QName _Code_QNAME = new QName("", "code");
    private final static QName _Herh_QNAME = new QName("", "herh");
    private final static QName _Mail_QNAME = new QName("", "mail");
    private final static QName _Volgnummer_QNAME = new QName("", "volgnummer");
    private final static QName _Icon_QNAME = new QName("", "icon");
    private final static QName _Medium_QNAME = new QName("", "medium");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _Srid_QNAME = new QName("", "srid");
    private final static QName _Omschrijving_QNAME = new QName("", "omschrijving");
    private final static QName _Titel_QNAME = new QName("", "titel");
    private final static QName _Afltitel_QNAME = new QName("", "afltitel");
    private final static QName _StartJaar_QNAME = new QName("", "start_jaar");
    private final static QName _Inbb_QNAME = new QName("", "inbb");
    private final static QName _Intt_QNAME = new QName("", "intt");
    private final static QName _Inhh_QNAME = new QName("", "inhh");
    private final static QName _Genre_QNAME = new QName("", "genre");
    private final static QName _Infi_QNAME = new QName("", "infi");
    private final static QName _Omroep_QNAME = new QName("", "omroep");
    private final static QName _Inhk_QNAME = new QName("", "inhk");
    private final static QName _Land_QNAME = new QName("", "land");
    private final static QName _Inh2_QNAME = new QName("", "inh2");
    private final static QName _Prem_QNAME = new QName("", "prem");
    private final static QName _LexicoTitel_QNAME = new QName("", "lexico_titel");
    private final static QName _Pridexport_QNAME = new QName("", "pridexport");
    private final static QName _Inh1_QNAME = new QName("", "inh1");
    private final static QName _Twitteraccount_QNAME = new QName("", "twitteraccount");
    private final static QName _AfgekorteTitel_QNAME = new QName("", "afgekorte_titel");
    private final static QName _Webs_QNAME = new QName("", "webs");
    private final static QName _Kykw_QNAME = new QName("", "kykw");
    private final static QName _Prid_QNAME = new QName("", "prid");
    private final static QName _GidsDatum_QNAME = new QName("", "gids_datum");
    private final static QName _Orti_QNAME = new QName("", "orti");
    private final static QName _Naam_QNAME = new QName("", "naam");
    private final static QName _Aflnr_QNAME = new QName("", "aflnr");
    private final static QName _Psrt_QNAME = new QName("", "psrt");
    private final static QName _Subgenre_QNAME = new QName("", "subgenre");
    private final static QName _Starttijd_QNAME = new QName("", "starttijd");
    private final static QName _Eindtijd_QNAME = new QName("", "eindtijd");
    private final static QName _Twitterhashtag_QNAME = new QName("", "twitterhashtag");
    private final static QName _Lcod_QNAME = new QName("", "lcod");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.vpro.domain.npo.projectm.metadata.v21
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Parentserie }
     *
     */
    public Parentserie createParentserie() {
        return new Parentserie();
    }

    /**
     * Create an instance of {@link Aflevering }
     *
     */
    public Aflevering createAflevering() {
        return new Aflevering();
    }

    /**
     * Create an instance of {@link Omroepen }
     *
     */
    public Omroepen createOmroepen() {
        return new Omroepen();
    }

    /**
     * Create an instance of {@link Personen }
     *
     */
    public Personen createPersonen() {
        return new Personen();
    }

    /**
     * Create an instance of {@link Persoon }
     *
     */
    public Persoon createPersoon() {
        return new Persoon();
    }

    /**
     * Create an instance of {@link Rol }
     *
     */
    public Rol createRol() {
        return new Rol();
    }

    /**
     * Create an instance of {@link Serie }
     *
     */
    public Serie createSerie() {
        return new Serie();
    }

    /**
     * Create an instance of {@link Uitzending }
     *
     */
    public Uitzending createUitzending() {
        return new Uitzending();
    }

    /**
     * Create an instance of {@link Zender }
     *
     */
    public Zender createZender() {
        return new Zender();
    }

    /**
     * Create an instance of {@link Uitzendingen }
     *
     */
    public Uitzendingen createUitzendingen() {
        return new Uitzendingen();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "bron")
    public JAXBElement<String> createBron(String value) {
        return new JAXBElement<>(_Bron_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "inh3")
    public JAXBElement<String> createInh3(String value) {
        return new JAXBElement<>(_Inh3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "gids_tekst")
    public JAXBElement<String> createGidsTekst(String value) {
        return new JAXBElement<>(_GidsTekst_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "code")
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "herh")
    public JAXBElement<String> createHerh(String value) {
        return new JAXBElement<>(_Herh_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "mail")
    public JAXBElement<String> createMail(String value) {
        return new JAXBElement<>(_Mail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "volgnummer")
    public JAXBElement<String> createVolgnummer(String value) {
        return new JAXBElement<>(_Volgnummer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "icon")
    public JAXBElement<String> createIcon(String value) {
        return new JAXBElement<>(_Icon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "medium")
    public JAXBElement<String> createMedium(String value) {
        return new JAXBElement<>(_Medium_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "srid")
    public JAXBElement<String> createSrid(String value) {
        return new JAXBElement<>(_Srid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "omschrijving")
    public JAXBElement<String> createOmschrijving(String value) {
        return new JAXBElement<>(_Omschrijving_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "titel")
    public JAXBElement<String> createTitel(String value) {
        return new JAXBElement<>(_Titel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "afltitel")
    public JAXBElement<String> createAfltitel(String value) {
        return new JAXBElement<>(_Afltitel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "start_jaar")
    public JAXBElement<BigInteger> createStartJaar(BigInteger value) {
        return new JAXBElement<>(_StartJaar_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "inbb")
    public JAXBElement<String> createInbb(String value) {
        return new JAXBElement<>(_Inbb_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "intt")
    public JAXBElement<String> createIntt(String value) {
        return new JAXBElement<>(_Intt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "inhh")
    public JAXBElement<String> createInhh(String value) {
        return new JAXBElement<>(_Inhh_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "genre")
    public JAXBElement<String> createGenre(String value) {
        return new JAXBElement<>(_Genre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "infi")
    public JAXBElement<String> createInfi(String value) {
        return new JAXBElement<>(_Infi_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "omroep")
    public JAXBElement<String> createOmroep(String value) {
        return new JAXBElement<>(_Omroep_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "inhk")
    public JAXBElement<String> createInhk(String value) {
        return new JAXBElement<>(_Inhk_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "land")
    public JAXBElement<String> createLand(String value) {
        return new JAXBElement<>(_Land_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "inh2")
    public JAXBElement<String> createInh2(String value) {
        return new JAXBElement<>(_Inh2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "prem")
    public JAXBElement<BigInteger> createPrem(BigInteger value) {
        return new JAXBElement<>(_Prem_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "lexico_titel")
    public JAXBElement<String> createLexicoTitel(String value) {
        return new JAXBElement<>(_LexicoTitel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "pridexport")
    public JAXBElement<String> createPridexport(String value) {
        return new JAXBElement<>(_Pridexport_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "inh1")
    public JAXBElement<String> createInh1(String value) {
        return new JAXBElement<>(_Inh1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "twitteraccount")
    public JAXBElement<String> createTwitteraccount(String value) {
        return new JAXBElement<>(_Twitteraccount_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "afgekorte_titel")
    public JAXBElement<String> createAfgekorteTitel(String value) {
        return new JAXBElement<>(_AfgekorteTitel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "webs")
    public JAXBElement<String> createWebs(String value) {
        return new JAXBElement<>(_Webs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "kykw")
    public JAXBElement<String> createKykw(String value) {
        return new JAXBElement<>(_Kykw_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "prid")
    public JAXBElement<String> createPrid(String value) {
        return new JAXBElement<>(_Prid_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "gids_datum")
    public JAXBElement<String> createGidsDatum(String value) {
        return new JAXBElement<>(_GidsDatum_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "orti")
    public JAXBElement<String> createOrti(String value) {
        return new JAXBElement<>(_Orti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "naam")
    public JAXBElement<String> createNaam(String value) {
        return new JAXBElement<>(_Naam_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "aflnr")
    public JAXBElement<String> createAflnr(String value) {
        return new JAXBElement<>(_Aflnr_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "psrt")
    public JAXBElement<String> createPsrt(String value) {
        return new JAXBElement<>(_Psrt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "subgenre")
    public JAXBElement<String> createSubgenre(String value) {
        return new JAXBElement<>(_Subgenre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "starttijd")
    public JAXBElement<XMLGregorianCalendar> createStarttijd(XMLGregorianCalendar value) {
        return new JAXBElement<>(_Starttijd_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "eindtijd")
    public JAXBElement<XMLGregorianCalendar> createEindtijd(XMLGregorianCalendar value) {
        return new JAXBElement<>(_Eindtijd_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "twitterhashtag")
    public JAXBElement<String> createTwitterhashtag(String value) {
        return new JAXBElement<>(_Twitterhashtag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "lcod")
    public JAXBElement<String> createLcod(String value) {
        return new JAXBElement<>(_Lcod_QNAME, String.class, null, value);
    }

}
