//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.21 at 10:52:28 AM CEST
//


package nl.vpro.domain.npo.projectm.metadata.v2_1;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}rol" minOccurs="0"/>
 *         &lt;element name="voornaam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="achternaam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "rol",
    "voornaam",
    "achternaam"
})
@XmlRootElement(name = "persoon")
public class Persoon {

    protected Rol rol;
    protected String voornaam;
    protected String achternaam;

    /**
     * Gets the value of the rol property.
     *
     * @return
     *     possible object is
     *     {@link Rol }
     *
     */
    public Rol getRol() {
        return rol;
    }

    /**
     * Sets the value of the rol property.
     *
     * @param value
     *     allowed object is
     *     {@link Rol }
     *
     */
    public void setRol(Rol value) {
        this.rol = value;
    }

    /**
     * Gets the value of the voornaam property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVoornaam() {
        return voornaam;
    }

    /**
     * Sets the value of the voornaam property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVoornaam(String value) {
        this.voornaam = value;
    }

    /**
     * Gets the value of the achternaam property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAchternaam() {
        return achternaam;
    }

    /**
     * Sets the value of the achternaam property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAchternaam(String value) {
        this.achternaam = value;
    }

}
