= Common Thesaurus for AudioVisual Archives (GTAA)
:toc:

This contains the 'openskos' client implementation of the link:https://www.beeldengeluid.nl/onderzoek/onderzoek/kennisthemas/metadata/gemeenschappelijke-thesaurus-audiovisuele-archieven[GTAA repository].

So this code produces the specific implementation of link:https://github.com/npo-poms/poms-shared/blob/main/gtaa-domain/src/main/java/nl/vpro/domain/gtaa/GTAARepository.java[GTAARepository]

== Axes

GTAA provides several axes ('schemes') of information. POMS uses several of them, but the must important one is the persons.

Every concept has its own unique 'gtaa id'.

The repository provides methods to

- Find persons or information from other schemes, in the GTAA of Beeld en Geluid.
- For some use cases it is important to sync data from the GTAA to your local database or so. Poms uses the several 'update' calls to inspect all changes and see if something needs change in its own database.
- It is also possible to submit new concepts to the GTAA in case one is missing. T


== Frontend code

Beeld en Geluid does not provide a frontend. The poms team made something and this is used in both poms, and can also be used in other frontends.

See https://github.com/npo-poms/thesaurus

== About OpenSKOS

It seems that 'open skos' (Used to be at http://openskos.org/) does not exist any more. BENG did rewrite it, and this required only minor changes on the client side.




=== Productie

https://gtaa.apis.beeldengeluid.nl/ Gives an overview.

=== Test

There is no test-environment nowadays.


=== Acceptatie

https://skos-acc.beeldengeluid.nl/







`
