//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.04.03 at 09:16:55 AM CEST
//


package nl.vpro.domain.npo.restriction.v2_2;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the nl.vpro.domain.npo.restriction.v2_2 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.vpro.domain.npo.restriction.v2_2
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Geoiprestrictie }
     *
     */
    public Geoiprestrictie createGeoiprestrictie() {
        return new Geoiprestrictie();
    }

    /**
     * Create an instance of {@link Encryptie }
     *
     */
    public Encryptie createEncryptie() {
        return new Encryptie();
    }

    /**
     * Create an instance of {@link Omroepen }
     *
     */
    public Omroepen createOmroepen() {
        return new Omroepen();
    }

    /**
     * Create an instance of {@link Restriction }
     *
     */
    public Restriction createRestriction() {
        return new Restriction();
    }

    /**
     * Create an instance of {@link Leeftijdsbeperking }
     *
     */
    public Leeftijdsbeperking createLeeftijdsbeperking() {
        return new Leeftijdsbeperking();
    }

    /**
     * Create an instance of {@link Tijdsbeperking }
     *
     */
    public Tijdsbeperking createTijdsbeperking() {
        return new Tijdsbeperking();
    }

}
