//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2018.04.03 at 09:16:55 AM CEST
//


package nl.vpro.domain.npo.restriction.v2_2;

import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pridexport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}geoiprestrictie" minOccurs="0"/>
 *         &lt;element ref="{}encryptie" minOccurs="0"/>
 *         &lt;element ref="{}leeftijdsbeperking" minOccurs="0"/>
 *         &lt;element ref="{}tijdsbeperking" minOccurs="0"/>
 *         &lt;element ref="{}omroepen"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prid",
    "pridexport",
    "titel",
    "platform",
    "geoiprestrictie",
    "encryptie",
    "leeftijdsbeperking",
    "tijdsbeperking",
    "omroepen"
})
@XmlRootElement(name = "restriction")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Restriction {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String prid;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String pridexport;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String titel;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String platform;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Geoiprestrictie geoiprestrictie;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Encryptie encryptie;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Leeftijdsbeperking leeftijdsbeperking;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Tijdsbeperking tijdsbeperking;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Omroepen omroepen;
    @XmlAttribute(name = "timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the prid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getPrid() {
        return prid;
    }

    /**
     * Sets the value of the prid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPrid(String value) {
        this.prid = value;
    }

    /**
     * Gets the value of the pridexport property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getPridexport() {
        return pridexport;
    }

    /**
     * Sets the value of the pridexport property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPridexport(String value) {
        this.pridexport = value;
    }

    /**
     * Gets the value of the titel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the platform property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the geoiprestrictie property.
     *
     * @return
     *     possible object is
     *     {@link Geoiprestrictie }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Geoiprestrictie getGeoiprestrictie() {
        return geoiprestrictie;
    }

    /**
     * Sets the value of the geoiprestrictie property.
     *
     * @param value
     *     allowed object is
     *     {@link Geoiprestrictie }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setGeoiprestrictie(Geoiprestrictie value) {
        this.geoiprestrictie = value;
    }

    /**
     * Gets the value of the encryptie property.
     *
     * @return
     *     possible object is
     *     {@link Encryptie }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Encryptie getEncryptie() {
        return encryptie;
    }

    /**
     * Sets the value of the encryptie property.
     *
     * @param value
     *     allowed object is
     *     {@link Encryptie }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setEncryptie(Encryptie value) {
        this.encryptie = value;
    }

    /**
     * Gets the value of the leeftijdsbeperking property.
     *
     * @return
     *     possible object is
     *     {@link Leeftijdsbeperking }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Leeftijdsbeperking getLeeftijdsbeperking() {
        return leeftijdsbeperking;
    }

    /**
     * Sets the value of the leeftijdsbeperking property.
     *
     * @param value
     *     allowed object is
     *     {@link Leeftijdsbeperking }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setLeeftijdsbeperking(Leeftijdsbeperking value) {
        this.leeftijdsbeperking = value;
    }

    /**
     * Gets the value of the tijdsbeperking property.
     *
     * @return
     *     possible object is
     *     {@link Tijdsbeperking }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Tijdsbeperking getTijdsbeperking() {
        return tijdsbeperking;
    }

    /**
     * Sets the value of the tijdsbeperking property.
     *
     * @param value
     *     allowed object is
     *     {@link Tijdsbeperking }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setTijdsbeperking(Tijdsbeperking value) {
        this.tijdsbeperking = value;
    }

    /**
     * Gets the value of the omroepen property.
     *
     * @return
     *     possible object is
     *     {@link Omroepen }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Omroepen getOmroepen() {
        return omroepen;
    }

    /**
     * Sets the value of the omroepen property.
     *
     * @param value
     *     allowed object is
     *     {@link Omroepen }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setOmroepen(Omroepen value) {
        this.omroepen = value;
    }

    /**
     * Gets the value of the timestamp property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2018-04-03T09:16:55+02:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

}
