//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.21 at 10:40:57 AM CEST
//


package nl.vpro.domain.npo.projectm.metadata.v3_2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pridexport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}titel"/>
 *         &lt;element ref="{}lexico_titel" minOccurs="0"/>
 *         &lt;element name="aflnr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="afltitel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}bron" minOccurs="0"/>
 *         &lt;element ref="{}orti" minOccurs="0"/>
 *         &lt;element name="prem" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element ref="{}lcod" minOccurs="0"/>
 *         &lt;element ref="{}icon" minOccurs="0"/>
 *         &lt;element name="kykw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inhr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inhk" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}inhl" minOccurs="0"/>
 *         &lt;element ref="{}genre" minOccurs="0"/>
 *         &lt;element ref="{}subgenre" minOccurs="0"/>
 *         &lt;element ref="{}psrt" minOccurs="0"/>
 *         &lt;element ref="{}mail" minOccurs="0"/>
 *         &lt;element ref="{}webs" minOccurs="0"/>
 *         &lt;element ref="{}twitteraccount" minOccurs="0"/>
 *         &lt;element ref="{}twitterhashtag" minOccurs="0"/>
 *         &lt;element ref="{}personen" minOccurs="0"/>
 *         &lt;element ref="{}omroepen"/>
 *         &lt;element ref="{}uitzendingen" minOccurs="0"/>
 *         &lt;element ref="{}serie" minOccurs="0"/>
 *         &lt;element ref="{}parentserie" minOccurs="0"/>
 *         &lt;element ref="{}promo" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prid",
    "pridexport",
    "titel",
    "lexicoTitel",
    "aflnr",
    "afltitel",
    "bron",
    "orti",
    "prem",
    "lcod",
    "icon",
    "kykw",
    "inhr",
    "inhk",
    "inhl",
    "genre",
    "subgenre",
    "psrt",
    "mail",
    "webs",
    "twitteraccount",
    "twitterhashtag",
    "personen",
    "omroepen",
    "uitzendingen",
    "serie",
    "parentserie",
    "promo"
})
@XmlRootElement(name = "aflevering")
public class Aflevering {

    @XmlElement(required = true)
    protected String prid;
    @XmlElement(required = true)
    protected String pridexport;
    @XmlElement(required = true)
    protected String titel;
    @XmlElement(name = "lexico_titel")
    protected String lexicoTitel;
    protected String aflnr;
    protected String afltitel;
    protected String bron;
    protected String orti;
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar prem;
    protected String lcod;
    @XmlSchemaType(name = "anyURI")
    protected String icon;
    protected String kykw;
    protected String inhr;
    protected String inhk;
    protected String inhl;
    protected String genre;
    protected String subgenre;
    protected String psrt;
    protected String mail;
    @XmlSchemaType(name = "anyURI")
    protected String webs;
    protected String twitteraccount;
    protected String twitterhashtag;
    protected Personen personen;
    @XmlElement(required = true)
    protected Omroepen omroepen;
    protected Uitzendingen uitzendingen;
    protected Serie serie;
    protected Parentserie parentserie;
    protected Promo promo;
    @XmlAttribute(name = "timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the prid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPrid() {
        return prid;
    }

    /**
     * Sets the value of the prid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrid(String value) {
        this.prid = value;
    }

    /**
     * Gets the value of the pridexport property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPridexport() {
        return pridexport;
    }

    /**
     * Sets the value of the pridexport property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPridexport(String value) {
        this.pridexport = value;
    }

    /**
     * Gets the value of the titel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the lexicoTitel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLexicoTitel() {
        return lexicoTitel;
    }

    /**
     * Sets the value of the lexicoTitel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLexicoTitel(String value) {
        this.lexicoTitel = value;
    }

    /**
     * Gets the value of the aflnr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAflnr() {
        return aflnr;
    }

    /**
     * Sets the value of the aflnr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAflnr(String value) {
        this.aflnr = value;
    }

    /**
     * Gets the value of the afltitel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAfltitel() {
        return afltitel;
    }

    /**
     * Sets the value of the afltitel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAfltitel(String value) {
        this.afltitel = value;
    }

    /**
     * Gets the value of the bron property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBron() {
        return bron;
    }

    /**
     * Sets the value of the bron property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBron(String value) {
        this.bron = value;
    }

    /**
     * Gets the value of the orti property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrti() {
        return orti;
    }

    /**
     * Sets the value of the orti property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrti(String value) {
        this.orti = value;
    }

    /**
     * Gets the value of the prem property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getPrem() {
        return prem;
    }

    /**
     * Sets the value of the prem property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setPrem(XMLGregorianCalendar value) {
        this.prem = value;
    }

    /**
     * Gets the value of the lcod property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLcod() {
        return lcod;
    }

    /**
     * Sets the value of the lcod property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLcod(String value) {
        this.lcod = value;
    }

    /**
     * Gets the value of the icon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIcon(String value) {
        this.icon = value;
    }

    /**
     * Gets the value of the kykw property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKykw() {
        return kykw;
    }

    /**
     * Sets the value of the kykw property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKykw(String value) {
        this.kykw = value;
    }

    /**
     * Gets the value of the inhr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInhr() {
        return inhr;
    }

    /**
     * Sets the value of the inhr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInhr(String value) {
        this.inhr = value;
    }

    /**
     * Gets the value of the inhk property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInhk() {
        return inhk;
    }

    /**
     * Sets the value of the inhk property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInhk(String value) {
        this.inhk = value;
    }

    /**
     * Gets the value of the inhl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInhl() {
        return inhl;
    }

    /**
     * Sets the value of the inhl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInhl(String value) {
        this.inhl = value;
    }

    /**
     * Gets the value of the genre property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGenre(String value) {
        this.genre = value;
    }

    /**
     * Gets the value of the subgenre property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubgenre() {
        return subgenre;
    }

    /**
     * Sets the value of the subgenre property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubgenre(String value) {
        this.subgenre = value;
    }

    /**
     * Gets the value of the psrt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPsrt() {
        return psrt;
    }

    /**
     * Sets the value of the psrt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPsrt(String value) {
        this.psrt = value;
    }

    /**
     * Gets the value of the mail property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the webs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWebs() {
        return webs;
    }

    /**
     * Sets the value of the webs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWebs(String value) {
        this.webs = value;
    }

    /**
     * Gets the value of the twitteraccount property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTwitteraccount() {
        return twitteraccount;
    }

    /**
     * Sets the value of the twitteraccount property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTwitteraccount(String value) {
        this.twitteraccount = value;
    }

    /**
     * Gets the value of the twitterhashtag property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTwitterhashtag() {
        return twitterhashtag;
    }

    /**
     * Sets the value of the twitterhashtag property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTwitterhashtag(String value) {
        this.twitterhashtag = value;
    }

    /**
     * Gets the value of the personen property.
     *
     * @return
     *     possible object is
     *     {@link Personen }
     *
     */
    public Personen getPersonen() {
        return personen;
    }

    /**
     * Sets the value of the personen property.
     *
     * @param value
     *     allowed object is
     *     {@link Personen }
     *
     */
    public void setPersonen(Personen value) {
        this.personen = value;
    }

    /**
     * Gets the value of the omroepen property.
     *
     * @return
     *     possible object is
     *     {@link Omroepen }
     *
     */
    public Omroepen getOmroepen() {
        return omroepen;
    }

    /**
     * Sets the value of the omroepen property.
     *
     * @param value
     *     allowed object is
     *     {@link Omroepen }
     *
     */
    public void setOmroepen(Omroepen value) {
        this.omroepen = value;
    }

    /**
     * Gets the value of the uitzendingen property.
     *
     * @return
     *     possible object is
     *     {@link Uitzendingen }
     *
     */
    public Uitzendingen getUitzendingen() {
        return uitzendingen;
    }

    /**
     * Sets the value of the uitzendingen property.
     *
     * @param value
     *     allowed object is
     *     {@link Uitzendingen }
     *
     */
    public void setUitzendingen(Uitzendingen value) {
        this.uitzendingen = value;
    }

    /**
     * Gets the value of the serie property.
     *
     * @return
     *     possible object is
     *     {@link Serie }
     *
     */
    public Serie getSerie() {
        return serie;
    }

    /**
     * Sets the value of the serie property.
     *
     * @param value
     *     allowed object is
     *     {@link Serie }
     *
     */
    public void setSerie(Serie value) {
        this.serie = value;
    }

    /**
     * Gets the value of the parentserie property.
     *
     * @return
     *     possible object is
     *     {@link Parentserie }
     *
     */
    public Parentserie getParentserie() {
        return parentserie;
    }

    /**
     * Sets the value of the parentserie property.
     *
     * @param value
     *     allowed object is
     *     {@link Parentserie }
     *
     */
    public void setParentserie(Parentserie value) {
        this.parentserie = value;
    }

    /**
     * Gets the value of the promo property.
     *
     * @return
     *     possible object is
     *     {@link Promo }
     *
     */
    public Promo getPromo() {
        return promo;
    }

    /**
     * Sets the value of the promo property.
     *
     * @param value
     *     allowed object is
     *     {@link Promo }
     *
     */
    public void setPromo(Promo value) {
        this.promo = value;
    }

    /**
     * Gets the value of the timestamp property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

}
