//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.21 at 10:40:57 AM CEST
//


package nl.vpro.domain.npo.projectm.metadata.v3_2;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the nl.vpro.domain.npo.projectm.metadata package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Bron_QNAME = new QName("", "bron");
    private final static QName _Mail_QNAME = new QName("", "mail");
    private final static QName _Icon_QNAME = new QName("", "icon");
    private final static QName _Webs_QNAME = new QName("", "webs");
    private final static QName _Orti_QNAME = new QName("", "orti");
    private final static QName _Psrt_QNAME = new QName("", "psrt");
    private final static QName _Titel_QNAME = new QName("", "titel");
    private final static QName _Subgenre_QNAME = new QName("", "subgenre");
    private final static QName _Inhl_QNAME = new QName("", "inhl");
    private final static QName _Genre_QNAME = new QName("", "genre");
    private final static QName _Twitterhashtag_QNAME = new QName("", "twitterhashtag");
    private final static QName _LexicoTitel_QNAME = new QName("", "lexico_titel");
    private final static QName _Lcod_QNAME = new QName("", "lcod");
    private final static QName _Twitteraccount_QNAME = new QName("", "twitteraccount");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.vpro.domain.npo.projectm.metadata
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Parentserie }
     *
     */
    public Parentserie createParentserie() {
        return new Parentserie();
    }

    /**
     * Create an instance of {@link Uitzendingen }
     *
     */
    public Uitzendingen createUitzendingen() {
        return new Uitzendingen();
    }

    /**
     * Create an instance of {@link Uitzending }
     *
     */
    public Uitzending createUitzending() {
        return new Uitzending();
    }

    /**
     * Create an instance of {@link Zender }
     *
     */
    public Zender createZender() {
        return new Zender();
    }

    /**
     * Create an instance of {@link Promo }
     *
     */
    public Promo createPromo() {
        return new Promo();
    }

    /**
     * Create an instance of {@link Aflevering }
     *
     */
    public Aflevering createAflevering() {
        return new Aflevering();
    }

    /**
     * Create an instance of {@link Personen }
     *
     */
    public Personen createPersonen() {
        return new Personen();
    }

    /**
     * Create an instance of {@link Persoon }
     *
     */
    public Persoon createPersoon() {
        return new Persoon();
    }

    /**
     * Create an instance of {@link Omroepen }
     *
     */
    public Omroepen createOmroepen() {
        return new Omroepen();
    }

    /**
     * Create an instance of {@link Serie }
     *
     */
    public Serie createSerie() {
        return new Serie();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "bron")
    public JAXBElement<String> createBron(String value) {
        return new JAXBElement<>(_Bron_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "mail")
    public JAXBElement<String> createMail(String value) {
        return new JAXBElement<>(_Mail_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "icon")
    public JAXBElement<String> createIcon(String value) {
        return new JAXBElement<>(_Icon_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "webs")
    public JAXBElement<String> createWebs(String value) {
        return new JAXBElement<>(_Webs_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "orti")
    public JAXBElement<String> createOrti(String value) {
        return new JAXBElement<>(_Orti_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "psrt")
    public JAXBElement<String> createPsrt(String value) {
        return new JAXBElement<>(_Psrt_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "titel")
    public JAXBElement<String> createTitel(String value) {
        return new JAXBElement<>(_Titel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "subgenre")
    public JAXBElement<String> createSubgenre(String value) {
        return new JAXBElement<>(_Subgenre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "inhl")
    public JAXBElement<String> createInhl(String value) {
        return new JAXBElement<>(_Inhl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "genre")
    public JAXBElement<String> createGenre(String value) {
        return new JAXBElement<>(_Genre_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "twitterhashtag")
    public JAXBElement<String> createTwitterhashtag(String value) {
        return new JAXBElement<>(_Twitterhashtag_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "lexico_titel")
    public JAXBElement<String> createLexicoTitel(String value) {
        return new JAXBElement<>(_LexicoTitel_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "lcod")
    public JAXBElement<String> createLcod(String value) {
        return new JAXBElement<>(_Lcod_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     *
     */
    @XmlElementDecl(namespace = "", name = "twitteraccount")
    public JAXBElement<String> createTwitteraccount(String value) {
        return new JAXBElement<>(_Twitteraccount_QNAME, String.class, null, value);
    }

}
