//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.21 at 10:40:57 AM CEST
//


package nl.vpro.domain.npo.projectm.metadata.v3_2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="psrid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}titel"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "psrid",
    "titel"
})
@XmlRootElement(name = "parentserie")
public class Parentserie {

    @XmlElement(required = true)
    protected String psrid;
    @XmlElement(required = true)
    protected String titel;

    /**
     * Gets the value of the psrid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPsrid() {
        return psrid;
    }

    /**
     * Sets the value of the psrid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPsrid(String value) {
        this.psrid = value;
    }

    /**
     * Gets the value of the titel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitel(String value) {
        this.titel = value;
    }

}
