//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.21 at 10:40:57 AM CEST
//


package nl.vpro.domain.npo.projectm.metadata.v3_2;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="promotedprid" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{}promo_type"/>
 *         &lt;element name="frames" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="starttijd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="eindtijd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "promotedprid",
    "type",
    "frames",
    "starttijd",
    "eindtijd"
})
@XmlRootElement(name = "promo")
public class Promo {

    protected String promotedprid;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected PromoType type;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger frames;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar starttijd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eindtijd;

    /**
     * Gets the value of the promotedprid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPromotedprid() {
        return promotedprid;
    }

    /**
     * Sets the value of the promotedprid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPromotedprid(String value) {
        this.promotedprid = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link PromoType }
     *
     */
    public PromoType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link PromoType }
     *
     */
    public void setType(PromoType value) {
        this.type = value;
    }

    /**
     * Gets the value of the frames property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getFrames() {
        return frames;
    }

    /**
     * Sets the value of the frames property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setFrames(BigInteger value) {
        this.frames = value;
    }

    /**
     * Gets the value of the starttijd property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getStarttijd() {
        return starttijd;
    }

    /**
     * Sets the value of the starttijd property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setStarttijd(XMLGregorianCalendar value) {
        this.starttijd = value;
    }

    /**
     * Gets the value of the eindtijd property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEindtijd() {
        return eindtijd;
    }

    /**
     * Sets the value of the eindtijd property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setEindtijd(XMLGregorianCalendar value) {
        this.eindtijd = value;
    }

}
