//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.21 at 10:40:57 AM CEST
//


package nl.vpro.domain.npo.projectm.metadata.v3_2;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="srid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}titel"/>
 *         &lt;element ref="{}lexico_titel" minOccurs="0"/>
 *         &lt;element ref="{}bron" minOccurs="0"/>
 *         &lt;element ref="{}orti" minOccurs="0"/>
 *         &lt;element name="start_jaar" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="seizoen" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{}lcod" minOccurs="0"/>
 *         &lt;element ref="{}icon" minOccurs="0"/>
 *         &lt;element ref="{}inhl" minOccurs="0"/>
 *         &lt;element ref="{}genre" minOccurs="0"/>
 *         &lt;element ref="{}subgenre" minOccurs="0"/>
 *         &lt;element ref="{}psrt" minOccurs="0"/>
 *         &lt;element ref="{}mail" minOccurs="0"/>
 *         &lt;element ref="{}webs" minOccurs="0"/>
 *         &lt;element ref="{}twitteraccount" minOccurs="0"/>
 *         &lt;element ref="{}twitterhashtag" minOccurs="0"/>
 *         &lt;element ref="{}omroepen" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "srid",
    "titel",
    "lexicoTitel",
    "bron",
    "orti",
    "startJaar",
    "seizoen",
    "lcod",
    "icon",
    "inhl",
    "genre",
    "subgenre",
    "psrt",
    "mail",
    "webs",
    "twitteraccount",
    "twitterhashtag",
    "omroepen"
})
@XmlRootElement(name = "serie")
public class Serie {

    @XmlElement(required = true)
    protected String srid;
    @XmlElement(required = true)
    protected String titel;
    @XmlElement(name = "lexico_titel")
    protected String lexicoTitel;
    protected String bron;
    protected String orti;
    @XmlElement(name = "start_jaar")
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar startJaar;
    protected String seizoen;
    protected String lcod;
    @XmlSchemaType(name = "anyURI")
    protected String icon;
    protected String inhl;
    protected String genre;
    protected String subgenre;
    protected String psrt;
    protected String mail;
    @XmlSchemaType(name = "anyURI")
    protected String webs;
    protected String twitteraccount;
    protected String twitterhashtag;
    protected Omroepen omroepen;

    /**
     * Gets the value of the srid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSrid() {
        return srid;
    }

    /**
     * Sets the value of the srid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSrid(String value) {
        this.srid = value;
    }

    /**
     * Gets the value of the titel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the lexicoTitel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLexicoTitel() {
        return lexicoTitel;
    }

    /**
     * Sets the value of the lexicoTitel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLexicoTitel(String value) {
        this.lexicoTitel = value;
    }

    /**
     * Gets the value of the bron property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBron() {
        return bron;
    }

    /**
     * Sets the value of the bron property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBron(String value) {
        this.bron = value;
    }

    /**
     * Gets the value of the orti property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrti() {
        return orti;
    }

    /**
     * Sets the value of the orti property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrti(String value) {
        this.orti = value;
    }

    /**
     * Gets the value of the startJaar property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getStartJaar() {
        return startJaar;
    }

    /**
     * Sets the value of the startJaar property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setStartJaar(XMLGregorianCalendar value) {
        this.startJaar = value;
    }

    /**
     * Gets the value of the seizoen property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSeizoen() {
        return seizoen;
    }

    /**
     * Sets the value of the seizoen property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSeizoen(String value) {
        this.seizoen = value;
    }

    /**
     * Gets the value of the lcod property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLcod() {
        return lcod;
    }

    /**
     * Sets the value of the lcod property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLcod(String value) {
        this.lcod = value;
    }

    /**
     * Gets the value of the icon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIcon(String value) {
        this.icon = value;
    }

    /**
     * Gets the value of the inhl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInhl() {
        return inhl;
    }

    /**
     * Sets the value of the inhl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInhl(String value) {
        this.inhl = value;
    }

    /**
     * Gets the value of the genre property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGenre() {
        return genre;
    }

    /**
     * Sets the value of the genre property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGenre(String value) {
        this.genre = value;
    }

    /**
     * Gets the value of the subgenre property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSubgenre() {
        return subgenre;
    }

    /**
     * Sets the value of the subgenre property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSubgenre(String value) {
        this.subgenre = value;
    }

    /**
     * Gets the value of the psrt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPsrt() {
        return psrt;
    }

    /**
     * Sets the value of the psrt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPsrt(String value) {
        this.psrt = value;
    }

    /**
     * Gets the value of the mail property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the webs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWebs() {
        return webs;
    }

    /**
     * Sets the value of the webs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWebs(String value) {
        this.webs = value;
    }

    /**
     * Gets the value of the twitteraccount property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTwitteraccount() {
        return twitteraccount;
    }

    /**
     * Sets the value of the twitteraccount property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTwitteraccount(String value) {
        this.twitteraccount = value;
    }

    /**
     * Gets the value of the twitterhashtag property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTwitterhashtag() {
        return twitterhashtag;
    }

    /**
     * Sets the value of the twitterhashtag property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTwitterhashtag(String value) {
        this.twitterhashtag = value;
    }

    /**
     * Gets the value of the omroepen property.
     *
     * @return
     *     possible object is
     *     {@link Omroepen }
     *
     */
    public Omroepen getOmroepen() {
        return omroepen;
    }

    /**
     * Sets the value of the omroepen property.
     *
     * @param value
     *     allowed object is
     *     {@link Omroepen }
     *
     */
    public void setOmroepen(Omroepen value) {
        this.omroepen = value;
    }

}
