//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.07.21 at 10:40:57 AM CEST
//


package nl.vpro.domain.npo.projectm.metadata.v3_2;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="gids_datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element ref="{}zender"/>
 *         &lt;element name="starttijd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="eindtijd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="herh" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="intt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="inhh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{}uitzending_type" minOccurs="0"/>
 *         &lt;element name="volgnummer" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gidsDatum",
    "zender",
    "starttijd",
    "eindtijd",
    "herh",
    "intt",
    "inhh",
    "type",
    "volgnummer"
})
@XmlRootElement(name = "uitzending")
public class Uitzending {

    @XmlElement(name = "gids_datum", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar gidsDatum;
    @XmlElement(required = true)
    protected Zender zender;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar starttijd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar eindtijd;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar herh;
    protected String intt;
    protected String inhh;
    @XmlSchemaType(name = "string")
    protected UitzendingType type;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger volgnummer;

    /**
     * Gets the value of the gidsDatum property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getGidsDatum() {
        return gidsDatum;
    }

    /**
     * Sets the value of the gidsDatum property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setGidsDatum(XMLGregorianCalendar value) {
        this.gidsDatum = value;
    }

    /**
     * Gets the value of the zender property.
     *
     * @return
     *     possible object is
     *     {@link Zender }
     *
     */
    public Zender getZender() {
        return zender;
    }

    /**
     * Sets the value of the zender property.
     *
     * @param value
     *     allowed object is
     *     {@link Zender }
     *
     */
    public void setZender(Zender value) {
        this.zender = value;
    }

    /**
     * Gets the value of the starttijd property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getStarttijd() {
        return starttijd;
    }

    /**
     * Sets the value of the starttijd property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setStarttijd(XMLGregorianCalendar value) {
        this.starttijd = value;
    }

    /**
     * Gets the value of the eindtijd property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEindtijd() {
        return eindtijd;
    }

    /**
     * Sets the value of the eindtijd property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setEindtijd(XMLGregorianCalendar value) {
        this.eindtijd = value;
    }

    /**
     * Gets the value of the herh property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getHerh() {
        return herh;
    }

    /**
     * Sets the value of the herh property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setHerh(XMLGregorianCalendar value) {
        this.herh = value;
    }

    /**
     * Gets the value of the intt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIntt() {
        return intt;
    }

    /**
     * Sets the value of the intt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIntt(String value) {
        this.intt = value;
    }

    /**
     * Gets the value of the inhh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInhh() {
        return inhh;
    }

    /**
     * Sets the value of the inhh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInhh(String value) {
        this.inhh = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link UitzendingType }
     *
     */
    public UitzendingType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link UitzendingType }
     *
     */
    public void setType(UitzendingType value) {
        this.type = value;
    }

    /**
     * Gets the value of the volgnummer property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getVolgnummer() {
        return volgnummer;
    }

    /**
     * Sets the value of the volgnummer property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setVolgnummer(BigInteger value) {
        this.volgnummer = value;
    }

}
