//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.12.05 at 11:14:06 AM CET
//


package nl.vpro.domain.npo.forecast.v2_0;

import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="prid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pridexport" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="platform" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gestopt" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{}uitzendingen"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prid",
    "pridexport",
    "platform",
    "gestopt",
    "titel",
    "uitzendingen"
})
@XmlRootElement(name = "aflevering")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Aflevering {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String prid;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String pridexport;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String platform;
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected int gestopt;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String titel;
    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected Uitzendingen uitzendingen;

    /**
     * Gets the value of the prid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getPrid() {
        return prid;
    }

    /**
     * Sets the value of the prid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPrid(String value) {
        this.prid = value;
    }

    /**
     * Gets the value of the pridexport property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getPridexport() {
        return pridexport;
    }

    /**
     * Sets the value of the pridexport property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPridexport(String value) {
        this.pridexport = value;
    }

    /**
     * Gets the value of the platform property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getPlatform() {
        return platform;
    }

    /**
     * Sets the value of the platform property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setPlatform(String value) {
        this.platform = value;
    }

    /**
     * Gets the value of the gestopt property.
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public int getGestopt() {
        return gestopt;
    }

    /**
     * Sets the value of the gestopt property.
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setGestopt(int value) {
        this.gestopt = value;
    }

    /**
     * Gets the value of the titel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the uitzendingen property.
     *
     * @return
     *     possible object is
     *     {@link Uitzendingen }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public Uitzendingen getUitzendingen() {
        return uitzendingen;
    }

    /**
     * Sets the value of the uitzendingen property.
     *
     * @param value
     *     allowed object is
     *     {@link Uitzendingen }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setUitzendingen(Uitzendingen value) {
        this.uitzendingen = value;
    }

}
