//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.12.05 at 11:14:06 AM CET
//


package nl.vpro.domain.npo.forecast.v2_0;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the nl.vpro.domain.npo.forecast.v2_0 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.vpro.domain.npo.forecast.v2_0
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Aflevering }
     *
     */
    public Aflevering createAflevering() {
        return new Aflevering();
    }

    /**
     * Create an instance of {@link Uitzendingen }
     *
     */
    public Uitzendingen createUitzendingen() {
        return new Uitzendingen();
    }

    /**
     * Create an instance of {@link Uitzending }
     *
     */
    public Uitzending createUitzending() {
        return new Uitzending();
    }

    /**
     * Create an instance of {@link Voorspellingen }
     *
     */
    public Voorspellingen createVoorspellingen() {
        return new Voorspellingen();
    }

}
