//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.12.05 at 11:14:06 AM CET
//


package nl.vpro.domain.npo.forecast.v2_0;

import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="starttijd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="eindtijd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zender",
    "starttijd",
    "eindtijd"
})
@XmlRootElement(name = "uitzending")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Uitzending {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String zender;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected XMLGregorianCalendar starttijd;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected XMLGregorianCalendar eindtijd;

    /**
     * Gets the value of the zender property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getZender() {
        return zender;
    }

    /**
     * Sets the value of the zender property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setZender(String value) {
        this.zender = value;
    }

    /**
     * Gets the value of the starttijd property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public XMLGregorianCalendar getStarttijd() {
        return starttijd;
    }

    /**
     * Sets the value of the starttijd property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setStarttijd(XMLGregorianCalendar value) {
        this.starttijd = value;
    }

    /**
     * Gets the value of the eindtijd property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public XMLGregorianCalendar getEindtijd() {
        return eindtijd;
    }

    /**
     * Sets the value of the eindtijd property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setEindtijd(XMLGregorianCalendar value) {
        this.eindtijd = value;
    }

}
