//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.12.05 at 11:14:06 AM CET
//


package nl.vpro.domain.npo.forecast.v2_0;

import java.util.ArrayList;
import java.util.List;
import jakarta.annotation.Generated;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}aflevering" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="einddatum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="startdatum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="timestamp" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "aflevering"
})
@XmlRootElement(name = "voorspellingen")
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
public class Voorspellingen {

    @XmlElement(required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected List<Aflevering> aflevering;
    @XmlAttribute(name = "einddatum", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String einddatum;
    @XmlAttribute(name = "startdatum", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected String startdatum;
    @XmlAttribute(name = "timestamp", required = true)
    @XmlSchemaType(name = "dateTime")
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the aflevering property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aflevering property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAflevering().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Aflevering }
     *
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public List<Aflevering> getAflevering() {
        if (aflevering == null) {
            aflevering = new ArrayList<Aflevering>();
        }
        return this.aflevering;
    }

    /**
     * Gets the value of the einddatum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getEinddatum() {
        return einddatum;
    }

    /**
     * Sets the value of the einddatum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setEinddatum(String value) {
        this.einddatum = value;
    }

    /**
     * Gets the value of the startdatum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public String getStartdatum() {
        return startdatum;
    }

    /**
     * Sets the value of the startdatum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setStartdatum(String value) {
        this.startdatum = value;
    }

    /**
     * Gets the value of the timestamp property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2016-12-05T11:14:06+01:00", comments = "JAXB RI v2.2.8-b130911.1802")
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

}
