//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0-b26-ea3
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.04.23 at 10:16:24 AM CEST
//


package nl.vpro.domain.media.support;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;

import nl.vpro.domain.Xmlns;


/**
 * The ordering of the enum values is relevant for its users
 *
 */
@XmlEnum
@XmlType(
    name = "textualTypeEnum",
    namespace = Xmlns.MEDIA_NAMESPACE
)
public enum TextualType {

    MAIN,
    SHORT,
    SUB,
    @Deprecated
    EPISODE,
    ORIGINAL,
    KICKER,
    LEXICO,
    WORK,
    ABBREVIATION;

    private final boolean isDeprecated;

    TextualType() {
        boolean dep;
        try {
            dep = OwnerType.class.getField(name()).isAnnotationPresent(Deprecated.class);
        } catch (Exception e) {
            dep = false;
        }
        isDeprecated = dep;
    }

    public boolean isDeprecated() {
        return isDeprecated;
    }


    public String value() {
        return name();
    }

    public TextualType fromValue(String v) {
        return TextualType.valueOf(v);
    }

}
