//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.07 at 01:34:44 PM CEST
//


package nl.vpro.domain.media.nebo.enrichment.v2_4;

import lombok.Getter;

import jakarta.xml.bind.annotation.*;

import nl.vpro.domain.media.Program;
import nl.vpro.domain.media.nebo.base.ImportType;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}aflevering"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{}versie use="required""/>
 *       &lt;attribute ref="{}type use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@Getter
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "aflevering"
        })
@XmlRootElement(name = "nebo_xml_import")
public class NeboXmlImport {

    @XmlElement(required = true)
    protected AfleveringType aflevering;

    @XmlAttribute(required = true)
    protected static final String versie = "2.3";

    @XmlAttribute(required = true)
    protected static final ImportType type = ImportType.VERRIJKING;

    public NeboXmlImport() {

    }

    public NeboXmlImport(Program program) {
        this.aflevering = new AfleveringType(program);
    }


    public void setAflevering(AfleveringType value) {
        this.aflevering = value;
    }

    public String getVersie() {
        return versie;
    }

    public void setVersie(String value) {
        if(!value.equals(this.versie)) {
            throw new IllegalArgumentException("This class supports NEBO enrichment version " + versie);
        }
    }

    public ImportType getType() {
        return type;
    }

    public void setType(ImportType value) {
        if(value != type)
            throw new IllegalArgumentException("This class supports NEBO enrichment type " + type);
    }

}
