//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2016.03.04 at 03:34:08 PM CET
//


package nl.vpro.domain.npo.streamstatus;

import javax.xml.bind.annotation.XmlRegistry;


@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.vpro.domain.npo.revoke.v3_0
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StreamStatus }
     *
     */
    public StreamStatus createStreamStatus() {
        return new StreamStatus();
    }


}
