//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.07 at 01:34:44 PM CEST
//


package nl.vpro.domain.media.nebo.base;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.*;

import nl.vpro.domain.image.ImageType;
import nl.vpro.domain.media.Program;
import nl.vpro.domain.media.support.Image;


/**
 * <p>Java class for afbeeldingenType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="afbeeldingenType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="afbeelding" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="omschrijving" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="trefwoorden" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *                 &lt;attribute name="slot" use="required" type="{http://namespace.com/importBase}slot" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="icon" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="omschrijving" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="trefwoorden" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="pad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "afbeeldingenType", propOrder = {
        "afbeelding",
        "icon"
        })
//@Deprecated (the Icon inner class is not deprecated)
public class AfbeeldingenType {

    protected List<AfbeeldingenType.Afbeelding> afbeelding;
    protected List<AfbeeldingenType.Icon> icon;

    public AfbeeldingenType() {
        // intelliJ requirement
    }

    public AfbeeldingenType(Program program) {
        List<Image> mediaImageList = program.getImages();
        afbeelding = new ArrayList<>();
        icon = new ArrayList<>();

        for (Image image : mediaImageList) {
            if (!image.getType().equals(ImageType.ICON)) {
                Afbeelding newAfbeelding = new Afbeelding();
                newAfbeelding.setOmschrijving(image.getDescription());
                newAfbeelding.setPad(image.getImageUri());
                newAfbeelding.setSlot(1); // DRS TODO: what is slot meant to hold?
                newAfbeelding.setTitel(image.getTitle());
                newAfbeelding.setTrefwoorden(""); // DRS TODO: can we get some keywords?
                this.afbeelding.add(newAfbeelding);
            } else {
                Icon newIcon = new Icon(image);
                this.icon.add(newIcon);

            }
        }

    }

    /**
     * Gets the value of the afbeelding property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the afbeelding property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAfbeelding().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AfbeeldingenType.Afbeelding }
     *
     *
     */
    public List<AfbeeldingenType.Afbeelding> getAfbeelding() {
        if (afbeelding == null) {
            afbeelding = new ArrayList<>();
        }
        return this.afbeelding;
    }

    /**
     * Gets the value of the icon property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the icon property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIcon().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AfbeeldingenType.Icon }
     *
     *
     */
    public List<AfbeeldingenType.Icon> getIcon() {
        if (icon == null) {
            icon = new ArrayList<>();
        }
        return this.icon;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="omschrijving" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="trefwoorden" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *       &lt;attribute name="slot" use="required" type="{http://namespace.com/importBase}slot" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            // Class is no longer in use
            })
    @Deprecated
    public static class Afbeelding {

        protected String titel;
        protected String omschrijving;
        protected String trefwoorden;
        protected String pad;
        @XmlAttribute(required = true)
        protected int slot;


        public String getTitel() {
            return titel;
        }

        public void setTitel(String value) {
            this.titel = value;
        }

        public String getOmschrijving() {
            return omschrijving;
        }


        public void setOmschrijving(String value) {
            this.omschrijving = value;
        }

        public String getTrefwoorden() {
            return trefwoorden;
        }


        public void setTrefwoorden(String value) {
            this.trefwoorden = value;
        }

        public String getPad() {
            return pad;
        }


        public void setPad(String value) {
            this.pad = value;
        }


        public int getSlot() {
            return slot;
        }

        public void setSlot(int value) {
            this.slot = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="omschrijving" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="trefwoorden" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="pad" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "titel",
            "omschrijving",
            "trefwoorden",
            "pad"
            })
    public static class Icon {

        protected String titel;
        protected String omschrijving;
        protected String trefwoorden;
        protected String pad;

        public Icon() {

        }
        public Icon(Image image) {
            setOmschrijving(image.getDescription());
            setPad(image.getImageUri());
            setTitel(image.getTitle());
            setTrefwoorden(""); // DRS TODO: can we get some keywords?
        }

        public String getTitel() {
            return titel;
        }


        public void setTitel(String value) {
            this.titel = value;
        }

        public String getOmschrijving() {
            return omschrijving;
        }

        public void setOmschrijving(String value) {
            this.omschrijving = value;
        }


        public String getTrefwoorden() {
            return trefwoorden;
        }

        public void setTrefwoorden(String value) {
            this.trefwoorden = value;
        }

        public String getPad() {
            return pad;
        }

        public void setPad(String value) {
            this.pad = value;
        }

    }

}
