//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.07 at 01:34:44 PM CEST
//


package nl.vpro.domain.media.nebo.base;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the nl.vpro.domain.media.nebo.base package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.vpro.domain.media.nebo.base
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TabsType }
     *
     */
    public TabsType createTabsType() {
        return new TabsType();
    }

    /**
     * Create an instance of {@link AfbeeldingenType }
     *
     */
    public AfbeeldingenType createAfbeeldingenType() {
        return new AfbeeldingenType();
    }

    /**
     * Create an instance of {@link OmroepenType }
     *
     */
    public OmroepenType createOmroepenType() {
        return new OmroepenType();
    }

    /**
     * Create an instance of {@link UitzendingType }
     *
     */
    public UitzendingType createUitzendingType() {
        return new UitzendingType();
    }

    /**
     * Create an instance of {@link GenresType }
     *
     */
    public GenresType createGenresType() {
        return new GenresType();
    }

    /**
     * Create an instance of {@link UitzendingenType }
     *
     */
    public UitzendingenType createUitzendingenType() {
        return new UitzendingenType();
    }

    /**
     * Create an instance of {@link TabsType.Tab }
     *
     */
    public TabsType.Tab createTabsTypeTab() {
        return new TabsType.Tab();
    }

    /**
     * Create an instance of {@link FragmentenType }
     *
     */
    public FragmentenType createFragmentenType() {
        return new FragmentenType();
    }

    /**
     * Create an instance of {@link AfbeeldingenType.Afbeelding }
     *
     */
    public AfbeeldingenType.Afbeelding createAfbeeldingenTypeAfbeelding() {
        return new AfbeeldingenType.Afbeelding();
    }

    /**
     * Create an instance of {@link FragmentenType.Fragment.Afbeelding }
     *
     */
    public FragmentenType.Fragment.Afbeelding createFragmentenTypeFragmentAfbeelding() {
        return new FragmentenType.Fragment.Afbeelding();
    }

    /**
     * Create an instance of {@link AfbeeldingenType.Icon }
     *
     */
    public AfbeeldingenType.Icon createAfbeeldingenTypeIcon() {
        return new AfbeeldingenType.Icon();
    }

    /**
     * Create an instance of {@link FragmentenType.Fragment }
     *
     */
    public FragmentenType.Fragment createFragmentenTypeFragment() {
        return new FragmentenType.Fragment();
    }

}
