//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.06.07 at 01:34:44 PM CEST
//


package nl.vpro.domain.media.nebo.base;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for uitzendingType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="uitzendingType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zenderkode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="gids_datum" type="{http://namespace.com/importBase}datum"/>
 *         &lt;element name="type" type="{http://namespace.com/importBase}koepelType"/>
 *         &lt;element name="begi" type="{http://namespace.com/importBase}datumtijd"/>
 *         &lt;element name="eind" type="{http://namespace.com/importBase}datumtijd"/>
 *         &lt;element name="intt" type="{http://namespace.com/importBase}teletekstType" minOccurs="0"/>
 *         &lt;element name="inhh" type="{http://namespace.com/importBase}herhalingType" minOccurs="0"/>
 *         &lt;element name="herh" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "uitzendingType", propOrder = {
        "zenderkode",
        "gidsDatum",
        "type",
        "begi",
        "eind",
        "intt",
        "inhh",
        "herh"
        })
public class UitzendingType {

    @XmlElement(required = true)
    protected String zenderkode;
    @XmlElement(name = "gids_datum", required = true)
    protected XMLGregorianCalendar gidsDatum;
    @XmlElement(required = true)
    protected KoepelType type;
    @XmlElement(required = true)
    protected XMLGregorianCalendar begi;
    @XmlElement(required = true)
    protected XMLGregorianCalendar eind;
    protected TeletekstType intt;
    protected HerhalingType inhh;
    protected String herh;

    /**
     * Gets the value of the zenderkode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getZenderkode() {
        return zenderkode;
    }

    /**
     * Sets the value of the zenderkode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setZenderkode(String value) {
        this.zenderkode = value;
    }

    /**
     * Gets the value of the gidsDatum property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getGidsDatum() {
        return gidsDatum;
    }

    /**
     * Sets the value of the gidsDatum property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setGidsDatum(XMLGregorianCalendar value) {
        this.gidsDatum = value;
    }

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link KoepelType }
     *
     */
    public KoepelType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link KoepelType }
     *
     */
    public void setType(KoepelType value) {
        this.type = value;
    }

    /**
     * Gets the value of the begi property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getBegi() {
        return begi;
    }

    /**
     * Sets the value of the begi property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setBegi(XMLGregorianCalendar value) {
        this.begi = value;
    }

    /**
     * Gets the value of the eind property.
     *
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public XMLGregorianCalendar getEind() {
        return eind;
    }

    /**
     * Sets the value of the eind property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *
     */
    public void setEind(XMLGregorianCalendar value) {
        this.eind = value;
    }

    /**
     * Gets the value of the intt property.
     *
     * @return
     *     possible object is
     *     {@link TeletekstType }
     *
     */
    public TeletekstType getIntt() {
        return intt;
    }

    /**
     * Sets the value of the intt property.
     *
     * @param value
     *     allowed object is
     *     {@link TeletekstType }
     *
     */
    public void setIntt(TeletekstType value) {
        this.intt = value;
    }

    /**
     * Gets the value of the inhh property.
     *
     * @return
     *     possible object is
     *     {@link HerhalingType }
     *
     */
    public HerhalingType getInhh() {
        return inhh;
    }

    /**
     * Sets the value of the inhh property.
     *
     * @param value
     *     allowed object is
     *     {@link HerhalingType }
     *
     */
    public void setInhh(HerhalingType value) {
        this.inhh = value;
    }

    /**
     * Gets the value of the herh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHerh() {
        return herh;
    }

    /**
     * Sets the value of the herh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHerh(String value) {
        this.herh = value;
    }

}
