//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.08.17 at 05:17:31 PM CEST
//


package nl.vpro.domain.media.nebo.historyimport;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}prid"/>
 *         &lt;element ref="{}srid" minOccurs="0"/>
 *         &lt;element ref="{}tite"/>
 *         &lt;element ref="{}atit" minOccurs="0"/>
 *         &lt;element ref="{}medium" minOccurs="0"/>
 *         &lt;element ref="{}icon" minOccurs="0"/>
 *         &lt;element ref="{}inkl" minOccurs="0"/>
 *         &lt;element ref="{}ingl" minOccurs="0"/>
 *         &lt;element ref="{}infi" minOccurs="0"/>
 *         &lt;element ref="{}inak" minOccurs="0"/>
 *         &lt;element ref="{}inds" minOccurs="0"/>
 *         &lt;element ref="{}inbb" minOccurs="0"/>
 *         &lt;element ref="{}kykw" minOccurs="0"/>
 *         &lt;element ref="{}orti" minOccurs="0"/>
 *         &lt;element ref="{}lcod" minOccurs="0"/>
 *         &lt;element ref="{}psrt" minOccurs="0"/>
 *         &lt;element ref="{}prem" minOccurs="0"/>
 *         &lt;element ref="{}inh1" minOccurs="0"/>
 *         &lt;element ref="{}inh2" minOccurs="0"/>
 *         &lt;element ref="{}bron" minOccurs="0"/>
 *         &lt;element ref="{}prij" minOccurs="0"/>
 *         &lt;element ref="{}inh3" minOccurs="0"/>
 *         &lt;element ref="{}mail" minOccurs="0"/>
 *         &lt;element ref="{}webs" minOccurs="0"/>
 *         &lt;element ref="{}inhk" minOccurs="0"/>
 *         &lt;element ref="{}gids_tekst" minOccurs="0"/>
 *         &lt;element ref="{}tite_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}icon_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}inh1_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}atit_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}inh2_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}inh3_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}inhk_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}mail_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}webs_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}gids_tekst_verrijking" minOccurs="0"/>
 *         &lt;element ref="{}omroepen"/>
 *         &lt;element ref="{}genres" minOccurs="0"/>
 *         &lt;element ref="{}personen" minOccurs="0"/>
 *         &lt;element ref="{}uitzendingen"/>
 *         &lt;element ref="{}streams"/>
 *         &lt;element ref="{}fragmenten" minOccurs="0"/>
 *         &lt;element ref="{}serie" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "prid",
    "srid",
    "tite",
    "atit",
    "medium",
    "icon",
    "inkl",
    "ingl",
    "infi",
    "inak",
    "inds",
    "inbb",
    "kykw",
    "orti",
    "lcod",
    "psrt",
    "prem",
    "inh1",
    "inh2",
    "bron",
    "prij",
    "inh3",
    "mail",
    "webs",
    "inhk",
    "gidsTekst",
    "titeVerrijking",
    "iconVerrijking",
    "inh1Verrijking",
    "atitVerrijking",
    "inh2Verrijking",
    "inh3Verrijking",
    "inhkVerrijking",
    "mailVerrijking",
    "websVerrijking",
    "gidsTekstVerrijking",
    "omroepen",
    "genres",
    "personen",
    "uitzendingen",
    "streams",
    "fragmenten",
    "serie"
})
@XmlRootElement(name = "aflevering")
public class Aflevering {

    @XmlElement(required = true)
    protected String prid;
    protected String srid;
    @XmlElement(required = true)
    protected String tite;
    protected String atit;
    protected String medium;
    protected String icon;
    protected String inkl;
    protected String ingl;
    protected String infi;
    protected String inak;
    protected String inds;
    protected String inbb;
    protected String kykw;
    protected String orti;
    protected String lcod;
    protected String psrt;
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger prem;
    protected String inh1;
    protected String inh2;
    protected String bron;
    protected String prij;
    protected String inh3;
    protected String mail;
    protected String webs;
    protected String inhk;
    @XmlElement(name = "gids_tekst")
    protected String gidsTekst;
    @XmlElement(name = "tite_verrijking")
    protected String titeVerrijking;
    @XmlElement(name = "icon_verrijking")
    protected String iconVerrijking;
    @XmlElement(name = "inh1_verrijking")
    protected String inh1Verrijking;
    @XmlElement(name = "atit_verrijking")
    protected String atitVerrijking;
    @XmlElement(name = "inh2_verrijking")
    protected String inh2Verrijking;
    @XmlElement(name = "inh3_verrijking")
    protected String inh3Verrijking;
    @XmlElement(name = "inhk_verrijking")
    protected String inhkVerrijking;
    @XmlElement(name = "mail_verrijking")
    protected String mailVerrijking;
    @XmlElement(name = "webs_verrijking")
    protected String websVerrijking;
    @XmlElement(name = "gids_tekst_verrijking")
    protected String gidsTekstVerrijking;
    @XmlElement(required = true)
    protected Omroepen omroepen;
    protected Genres genres;
    protected Personen personen;
    @XmlElement(required = true)
    protected Uitzendingen uitzendingen;
    @XmlElement(required = true)
    protected Streams streams;
    protected Fragmenten fragmenten;
    protected Serie serie;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger id;

    /**
     * Gets the value of the prid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPrid() {
        return prid;
    }

    /**
     * Sets the value of the prid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrid(String value) {
        this.prid = value;
    }

    /**
     * Gets the value of the srid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getSrid() {
        return srid;
    }

    /**
     * Sets the value of the srid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setSrid(String value) {
        this.srid = value;
    }

    /**
     * Gets the value of the tite property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTite() {
        return tite;
    }

    /**
     * Sets the value of the tite property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTite(String value) {
        this.tite = value;
    }

    /**
     * Gets the value of the atit property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAtit() {
        return atit;
    }

    /**
     * Sets the value of the atit property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAtit(String value) {
        this.atit = value;
    }

    /**
     * Gets the value of the medium property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMedium() {
        return medium;
    }

    /**
     * Sets the value of the medium property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMedium(String value) {
        this.medium = value;
    }

    /**
     * Gets the value of the icon property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIcon(String value) {
        this.icon = value;
    }

    /**
     * Gets the value of the inkl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInkl() {
        return inkl;
    }

    /**
     * Sets the value of the inkl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInkl(String value) {
        this.inkl = value;
    }

    /**
     * Gets the value of the ingl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIngl() {
        return ingl;
    }

    /**
     * Sets the value of the ingl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIngl(String value) {
        this.ingl = value;
    }

    /**
     * Gets the value of the infi property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInfi() {
        return infi;
    }

    /**
     * Sets the value of the infi property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInfi(String value) {
        this.infi = value;
    }

    /**
     * Gets the value of the inak property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInak() {
        return inak;
    }

    /**
     * Sets the value of the inak property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInak(String value) {
        this.inak = value;
    }

    /**
     * Gets the value of the inds property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInds() {
        return inds;
    }

    /**
     * Sets the value of the inds property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInds(String value) {
        this.inds = value;
    }

    /**
     * Gets the value of the inbb property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInbb() {
        return inbb;
    }

    /**
     * Sets the value of the inbb property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInbb(String value) {
        this.inbb = value;
    }

    /**
     * Gets the value of the kykw property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getKykw() {
        return kykw;
    }

    /**
     * Sets the value of the kykw property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setKykw(String value) {
        this.kykw = value;
    }

    /**
     * Gets the value of the orti property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOrti() {
        return orti;
    }

    /**
     * Sets the value of the orti property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOrti(String value) {
        this.orti = value;
    }

    /**
     * Gets the value of the lcod property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getLcod() {
        return lcod;
    }

    /**
     * Sets the value of the lcod property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setLcod(String value) {
        this.lcod = value;
    }

    /**
     * Gets the value of the psrt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPsrt() {
        return psrt;
    }

    /**
     * Sets the value of the psrt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPsrt(String value) {
        this.psrt = value;
    }

    /**
     * Gets the value of the prem property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getPrem() {
        return prem;
    }

    /**
     * Sets the value of the prem property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setPrem(BigInteger value) {
        this.prem = value;
    }

    /**
     * Gets the value of the inh1 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInh1() {
        return inh1;
    }

    /**
     * Sets the value of the inh1 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInh1(String value) {
        this.inh1 = value;
    }

    /**
     * Gets the value of the inh2 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInh2() {
        return inh2;
    }

    /**
     * Sets the value of the inh2 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInh2(String value) {
        this.inh2 = value;
    }

    /**
     * Gets the value of the bron property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBron() {
        return bron;
    }

    /**
     * Sets the value of the bron property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBron(String value) {
        this.bron = value;
    }

    /**
     * Gets the value of the prij property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPrij() {
        return prij;
    }

    /**
     * Sets the value of the prij property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPrij(String value) {
        this.prij = value;
    }

    /**
     * Gets the value of the inh3 property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInh3() {
        return inh3;
    }

    /**
     * Sets the value of the inh3 property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInh3(String value) {
        this.inh3 = value;
    }

    /**
     * Gets the value of the mail property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the webs property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWebs() {
        return webs;
    }

    /**
     * Sets the value of the webs property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWebs(String value) {
        this.webs = value;
    }

    /**
     * Gets the value of the inhk property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInhk() {
        return inhk;
    }

    /**
     * Sets the value of the inhk property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInhk(String value) {
        this.inhk = value;
    }

    /**
     * Gets the value of the gidsTekst property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGidsTekst() {
        return gidsTekst;
    }

    /**
     * Sets the value of the gidsTekst property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGidsTekst(String value) {
        this.gidsTekst = value;
    }

    /**
     * Gets the value of the titeVerrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTiteVerrijking() {
        return titeVerrijking;
    }

    /**
     * Sets the value of the titeVerrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTiteVerrijking(String value) {
        this.titeVerrijking = value;
    }

    /**
     * Gets the value of the iconVerrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIconVerrijking() {
        return iconVerrijking;
    }

    /**
     * Sets the value of the iconVerrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIconVerrijking(String value) {
        this.iconVerrijking = value;
    }

    /**
     * Gets the value of the inh1Verrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInh1Verrijking() {
        return inh1Verrijking;
    }

    /**
     * Sets the value of the inh1Verrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInh1Verrijking(String value) {
        this.inh1Verrijking = value;
    }

    /**
     * Gets the value of the atitVerrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAtitVerrijking() {
        return atitVerrijking;
    }

    /**
     * Sets the value of the atitVerrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAtitVerrijking(String value) {
        this.atitVerrijking = value;
    }

    /**
     * Gets the value of the inh2Verrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInh2Verrijking() {
        return inh2Verrijking;
    }

    /**
     * Sets the value of the inh2Verrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInh2Verrijking(String value) {
        this.inh2Verrijking = value;
    }

    /**
     * Gets the value of the inh3Verrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInh3Verrijking() {
        return inh3Verrijking;
    }

    /**
     * Sets the value of the inh3Verrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInh3Verrijking(String value) {
        this.inh3Verrijking = value;
    }

    /**
     * Gets the value of the inhkVerrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInhkVerrijking() {
        return inhkVerrijking;
    }

    /**
     * Sets the value of the inhkVerrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInhkVerrijking(String value) {
        this.inhkVerrijking = value;
    }

    /**
     * Gets the value of the mailVerrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getMailVerrijking() {
        return mailVerrijking;
    }

    /**
     * Sets the value of the mailVerrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setMailVerrijking(String value) {
        this.mailVerrijking = value;
    }

    /**
     * Gets the value of the websVerrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWebsVerrijking() {
        return websVerrijking;
    }

    /**
     * Sets the value of the websVerrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWebsVerrijking(String value) {
        this.websVerrijking = value;
    }

    /**
     * Gets the value of the gidsTekstVerrijking property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGidsTekstVerrijking() {
        return gidsTekstVerrijking;
    }

    /**
     * Sets the value of the gidsTekstVerrijking property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGidsTekstVerrijking(String value) {
        this.gidsTekstVerrijking = value;
    }

    /**
     * Gets the value of the omroepen property.
     *
     * @return
     *     possible object is
     *     {@link Omroepen }
     *
     */
    public Omroepen getOmroepen() {
        return omroepen;
    }

    /**
     * Sets the value of the omroepen property.
     *
     * @param value
     *     allowed object is
     *     {@link Omroepen }
     *
     */
    public void setOmroepen(Omroepen value) {
        this.omroepen = value;
    }

    /**
     * Gets the value of the genres property.
     *
     * @return
     *     possible object is
     *     {@link Genres }
     *
     */
    public Genres getGenres() {
        return genres;
    }

    /**
     * Sets the value of the genres property.
     *
     * @param value
     *     allowed object is
     *     {@link Genres }
     *
     */
    public void setGenres(Genres value) {
        this.genres = value;
    }

    /**
     * Gets the value of the personen property.
     *
     * @return
     *     possible object is
     *     {@link Personen }
     *
     */
    public Personen getPersonen() {
        return personen;
    }

    /**
     * Sets the value of the personen property.
     *
     * @param value
     *     allowed object is
     *     {@link Personen }
     *
     */
    public void setPersonen(Personen value) {
        this.personen = value;
    }

    /**
     * Gets the value of the uitzendingen property.
     *
     * @return
     *     possible object is
     *     {@link Uitzendingen }
     *
     */
    public Uitzendingen getUitzendingen() {
        return uitzendingen;
    }

    /**
     * Sets the value of the uitzendingen property.
     *
     * @param value
     *     allowed object is
     *     {@link Uitzendingen }
     *
     */
    public void setUitzendingen(Uitzendingen value) {
        this.uitzendingen = value;
    }

    /**
     * Gets the value of the streams property.
     *
     * @return
     *     possible object is
     *     {@link Streams }
     *
     */
    public Streams getStreams() {
        return streams;
    }

    /**
     * Sets the value of the streams property.
     *
     * @param value
     *     allowed object is
     *     {@link Streams }
     *
     */
    public void setStreams(Streams value) {
        this.streams = value;
    }

    /**
     * Gets the value of the fragmenten property.
     *
     * @return
     *     possible object is
     *     {@link Fragmenten }
     *
     */
    public Fragmenten getFragmenten() {
        return fragmenten;
    }

    /**
     * Sets the value of the fragmenten property.
     *
     * @param value
     *     allowed object is
     *     {@link Fragmenten }
     *
     */
    public void setFragmenten(Fragmenten value) {
        this.fragmenten = value;
    }

    /**
     * Gets the value of the serie property.
     *
     * @return
     *     possible object is
     *     {@link Serie }
     *
     */
    public Serie getSerie() {
        return serie;
    }

    /**
     * Sets the value of the serie property.
     *
     * @param value
     *     allowed object is
     *     {@link Serie }
     *
     */
    public void setSerie(Serie value) {
        this.serie = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
