//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.08.17 at 05:17:31 PM CEST
//


package nl.vpro.domain.media.nebo.historyimport;

import java.math.BigInteger;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}titel"/>
 *         &lt;element ref="{}omschrijving" minOccurs="0"/>
 *         &lt;element ref="{}trefwoorden" minOccurs="0"/>
 *         &lt;element ref="{}starttijd"/>
 *         &lt;element ref="{}eindtijd"/>
 *         &lt;element ref="{}wijzigingsdatum"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titel",
    "omschrijving",
    "trefwoorden",
    "starttijd",
    "eindtijd",
    "wijzigingsdatum"
})
@XmlRootElement(name = "fragment")
public class Fragment {

    @XmlElement(required = true)
    protected String titel;
    protected String omschrijving;
    protected String trefwoorden;
    @XmlElement(required = true)
    protected String starttijd;
    @XmlElement(required = true)
    protected String eindtijd;
    @XmlElement(required = true)
    protected String wijzigingsdatum;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger id;

    /**
     * Gets the value of the titel property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the omschrijving property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getOmschrijving() {
        return omschrijving;
    }

    /**
     * Sets the value of the omschrijving property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setOmschrijving(String value) {
        this.omschrijving = value;
    }

    /**
     * Gets the value of the trefwoorden property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTrefwoorden() {
        return trefwoorden;
    }

    /**
     * Sets the value of the trefwoorden property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTrefwoorden(String value) {
        this.trefwoorden = value;
    }

    /**
     * Gets the value of the starttijd property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getStarttijd() {
        return starttijd;
    }

    /**
     * Sets the value of the starttijd property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setStarttijd(String value) {
        this.starttijd = value;
    }

    /**
     * Gets the value of the eindtijd property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEindtijd() {
        return eindtijd;
    }

    /**
     * Sets the value of the eindtijd property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEindtijd(String value) {
        this.eindtijd = value;
    }

    /**
     * Gets the value of the wijzigingsdatum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWijzigingsdatum() {
        return wijzigingsdatum;
    }

    /**
     * Sets the value of the wijzigingsdatum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWijzigingsdatum(String value) {
        this.wijzigingsdatum = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return
     *     possible object is
     *     {@link BigInteger }
     *
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
