//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.08.17 at 05:17:31 PM CEST
//


package nl.vpro.domain.media.nebo.historyimport;

import java.math.BigInteger;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}titel"/>
 *         &lt;element ref="{}lexico_titel" minOccurs="0"/>
 *         &lt;element ref="{}srids" minOccurs="0"/>
 *         &lt;element ref="{}omschrijving" minOccurs="0"/>
 *         &lt;element ref="{}icon" minOccurs="0"/>
 *         &lt;element ref="{}start_jaar" minOccurs="0"/>
 *         &lt;element ref="{}orti" minOccurs="0"/>
 *         &lt;element ref="{}lcod" minOccurs="0"/>
 *         &lt;element ref="{}psrt" minOccurs="0"/>
 *         &lt;element ref="{}inh1" minOccurs="0"/>
 *         &lt;element ref="{}bron" minOccurs="0"/>
 *         &lt;element ref="{}prij" minOccurs="0"/>
 *         &lt;element ref="{}inh3" minOccurs="0"/>
 *         &lt;element ref="{}mail" minOccurs="0"/>
 *         &lt;element ref="{}webs" minOccurs="0"/>
 *         &lt;element ref="{}gids_tekst" minOccurs="0"/>
 *         &lt;element ref="{}rss_url" minOccurs="0"/>
 *         &lt;element ref="{}omroepen"/>
 *         &lt;element ref="{}genres" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titel",
    "lexicoTitel",
    "srids",
    "omschrijving",
    "icon",
    "startJaar",
    "orti",
    "lcod",
    "psrt",
    "inh1",
    "bron",
    "prij",
    "inh3",
    "mail",
    "webs",
    "gidsTekst",
    "rssUrl",
    "omroepen",
    "genres"
})
@XmlRootElement(name = "serie")
public class Serie {

    @XmlElement(required = true)
    protected String titel;

    @XmlElement(name = "lexico_titel")
    protected String lexicoTitel;

    protected Srids srids;

    protected String omschrijving;

    protected String icon;

    @XmlElement(name = "start_jaar")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger startJaar;

    protected String orti;

    protected String lcod;

    protected String psrt;

    protected String inh1;

    protected String bron;

    protected String prij;

    protected String inh3;

    protected String mail;

    protected String webs;

    @XmlElement(name = "gids_tekst")
    protected String gidsTekst;

    @XmlElement(name = "rss_url")
    protected String rssUrl;

    @XmlElement(required = true)
    protected Omroepen omroepen;

    protected Genres genres;

    @XmlAttribute(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger id;

    /**
     * Gets the value of the titel property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the lexicoTitel property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLexicoTitel() {
        return lexicoTitel;
    }

    /**
     * Sets the value of the lexicoTitel property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLexicoTitel(String value) {
        this.lexicoTitel = value;
    }

    /**
     * Gets the value of the srids property.
     *
     * @return possible object is
     *         {@link Srids }
     */
    public Srids getSrids() {
        return srids;
    }

    /**
     * Sets the value of the srids property.
     *
     * @param value allowed object is
     *              {@link Srids }
     */
    public void setSrids(Srids value) {
        this.srids = value;
    }

    /**
     * Gets the value of the omschrijving property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getOmschrijving() {
        return omschrijving;
    }

    /**
     * Sets the value of the omschrijving property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOmschrijving(String value) {
        this.omschrijving = value;
    }

    /**
     * Gets the value of the icon property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setIcon(String value) {
        this.icon = value;
    }

    /**
     * Gets the value of the startJaar property.
     *
     * @return possible object is
     *         {@link BigInteger }
     */
    public BigInteger getStartJaar() {
        return startJaar;
    }

    /**
     * Sets the value of the startJaar property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setStartJaar(BigInteger value) {
        this.startJaar = value;
    }

    /**
     * Gets the value of the orti property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getOrti() {
        return orti;
    }

    /**
     * Sets the value of the orti property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOrti(String value) {
        this.orti = value;
    }

    /**
     * Gets the value of the lcod property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getLcod() {
        return lcod;
    }

    /**
     * Sets the value of the lcod property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setLcod(String value) {
        this.lcod = value;
    }

    /**
     * Gets the value of the psrt property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPsrt() {
        return psrt;
    }

    /**
     * Sets the value of the psrt property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPsrt(String value) {
        this.psrt = value;
    }

    /**
     * Gets the value of the inh1 property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getInh1() {
        return inh1;
    }

    /**
     * Sets the value of the inh1 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInh1(String value) {
        this.inh1 = value;
    }

    /**
     * Gets the value of the bron property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getBron() {
        return bron;
    }

    /**
     * Sets the value of the bron property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setBron(String value) {
        this.bron = value;
    }

    /**
     * Gets the value of the prij property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getPrij() {
        return prij;
    }

    /**
     * Sets the value of the prij property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setPrij(String value) {
        this.prij = value;
    }

    /**
     * Gets the value of the inh3 property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getInh3() {
        return inh3;
    }

    /**
     * Sets the value of the inh3 property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setInh3(String value) {
        this.inh3 = value;
    }

    /**
     * Gets the value of the mail property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getMail() {
        return mail;
    }

    /**
     * Sets the value of the mail property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setMail(String value) {
        this.mail = value;
    }

    /**
     * Gets the value of the webs property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getWebs() {
        return webs;
    }

    /**
     * Sets the value of the webs property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setWebs(String value) {
        this.webs = value;
    }

    /**
     * Gets the value of the gidsTekst property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getGidsTekst() {
        return gidsTekst;
    }

    /**
     * Sets the value of the gidsTekst property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setGidsTekst(String value) {
        this.gidsTekst = value;
    }

    /**
     * Gets the value of the rssUrl property.
     *
     * @return possible object is
     *         {@link String }
     */
    public String getRssUrl() {
        return rssUrl;
    }

    /**
     * Sets the value of the rssUrl property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setRssUrl(String value) {
        this.rssUrl = value;
    }

    /**
     * Gets the value of the omroepen property.
     *
     * @return possible object is
     *         {@link Omroepen }
     */
    public Omroepen getOmroepen() {
        return omroepen;
    }

    /**
     * Sets the value of the omroepen property.
     *
     * @param value allowed object is
     *              {@link Omroepen }
     */
    public void setOmroepen(Omroepen value) {
        this.omroepen = value;
    }

    /**
     * Gets the value of the genres property.
     *
     * @return possible object is
     *         {@link Genres }
     */
    public Genres getGenres() {
        return genres;
    }

    /**
     * Sets the value of the genres property.
     *
     * @param value allowed object is
     *              {@link Genres }
     */
    public void setGenres(Genres value) {
        this.genres = value;
    }

    /**
     * Gets the value of the id property.
     *
     * @return possible object is
     *         {@link BigInteger }
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     *
     * @param value allowed object is
     *              {@link BigInteger }
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

}
