//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.08.17 at 05:17:31 PM CEST
//


package nl.vpro.domain.media.nebo.historyimport;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}player_url"/>
 *         &lt;element ref="{}stream" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="webcast_toegestaan" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="publicatie_start" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="publicatie_eind" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="aspect_ratio" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "playerUrl",
    "stream"
})
@XmlRootElement(name = "streams")
public class Streams {

    @XmlElement(name = "player_url", required = true)
    protected String playerUrl;
    @XmlElement(required = true)
    protected List<Stream> stream;
    @XmlAttribute(name = "webcast_toegestaan", required = true)
    protected String webcastToegestaan;
    @XmlAttribute(name = "publicatie_start", required = true)
    protected String publicatieStart;
    @XmlAttribute(name = "publicatie_eind", required = true)
    protected String publicatieEind;
    @XmlAttribute(name = "aspect_ratio", required = true)
    protected String aspectRatio;

    /**
     * Gets the value of the playerUrl property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPlayerUrl() {
        return playerUrl;
    }

    /**
     * Sets the value of the playerUrl property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPlayerUrl(String value) {
        this.playerUrl = value;
    }

    /**
     * Gets the value of the stream property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stream property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStream().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stream }
     *
     *
     */
    public List<Stream> getStream() {
        if (stream == null) {
            stream = new ArrayList<>();
        }
        return this.stream;
    }

    /**
     * Gets the value of the webcastToegestaan property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWebcastToegestaan() {
        return webcastToegestaan;
    }

    /**
     * Sets the value of the webcastToegestaan property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWebcastToegestaan(String value) {
        this.webcastToegestaan = value;
    }

    /**
     * Gets the value of the publicatieStart property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPublicatieStart() {
        return publicatieStart;
    }

    /**
     * Sets the value of the publicatieStart property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPublicatieStart(String value) {
        this.publicatieStart = value;
    }

    /**
     * Gets the value of the publicatieEind property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPublicatieEind() {
        return publicatieEind;
    }

    /**
     * Sets the value of the publicatieEind property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPublicatieEind(String value) {
        this.publicatieEind = value;
    }

    /**
     * Gets the value of the aspectRatio property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAspectRatio() {
        return aspectRatio;
    }

    /**
     * Sets the value of the aspectRatio property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAspectRatio(String value) {
        this.aspectRatio = value;
    }

}
