//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2012.08.17 at 05:17:31 PM CEST
//


package nl.vpro.domain.media.nebo.historyimport;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}type" minOccurs="0"/>
 *         &lt;element ref="{}gids_datum"/>
 *         &lt;element ref="{}begi"/>
 *         &lt;element ref="{}eind"/>
 *         &lt;element ref="{}zender"/>
 *         &lt;element ref="{}inci" minOccurs="0"/>
 *         &lt;element ref="{}intt" minOccurs="0"/>
 *         &lt;element ref="{}inhh" minOccurs="0"/>
 *         &lt;element ref="{}herh" minOccurs="0"/>
 *         &lt;element ref="{}vpsc" minOccurs="0"/>
 *         &lt;element ref="{}ttpg" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="pepeid" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "type",
    "gidsDatum",
    "begi",
    "eind",
    "zender",
    "inci",
    "intt",
    "inhh",
    "herh",
    "vpsc",
    "ttpg"
})
@XmlRootElement(name = "uitzending")
public class Uitzending {

    protected String type;
    @XmlElement(name = "gids_datum", required = true)
    protected String gidsDatum;
    @XmlElement(required = true)
    protected String begi;
    @XmlElement(required = true)
    protected String eind;
    @XmlElement(required = true)
    protected Zender zender;
    protected String inci;
    protected String intt;
    protected String inhh;
    protected String herh;
    protected String vpsc;
    protected String ttpg;
    @XmlAttribute(required = true)
    protected String pepeid;

    /**
     * Gets the value of the type property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the gidsDatum property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getGidsDatum() {
        return gidsDatum;
    }

    /**
     * Sets the value of the gidsDatum property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setGidsDatum(String value) {
        this.gidsDatum = value;
    }

    /**
     * Gets the value of the begi property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getBegi() {
        return begi;
    }

    /**
     * Sets the value of the begi property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setBegi(String value) {
        this.begi = value;
    }

    /**
     * Gets the value of the eind property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEind() {
        return eind;
    }

    /**
     * Sets the value of the eind property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEind(String value) {
        this.eind = value;
    }

    /**
     * Gets the value of the zender property.
     *
     * @return
     *     possible object is
     *     {@link Zender }
     *
     */
    public Zender getZender() {
        return zender;
    }

    /**
     * Sets the value of the zender property.
     *
     * @param value
     *     allowed object is
     *     {@link Zender }
     *
     */
    public void setZender(Zender value) {
        this.zender = value;
    }

    /**
     * Gets the value of the inci property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInci() {
        return inci;
    }

    /**
     * Sets the value of the inci property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInci(String value) {
        this.inci = value;
    }

    /**
     * Gets the value of the intt property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getIntt() {
        return intt;
    }

    /**
     * Sets the value of the intt property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setIntt(String value) {
        this.intt = value;
    }

    /**
     * Gets the value of the inhh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getInhh() {
        return inhh;
    }

    /**
     * Sets the value of the inhh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setInhh(String value) {
        this.inhh = value;
    }

    /**
     * Gets the value of the herh property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getHerh() {
        return herh;
    }

    /**
     * Sets the value of the herh property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setHerh(String value) {
        this.herh = value;
    }

    /**
     * Gets the value of the vpsc property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getVpsc() {
        return vpsc;
    }

    /**
     * Sets the value of the vpsc property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setVpsc(String value) {
        this.vpsc = value;
    }

    /**
     * Gets the value of the ttpg property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTtpg() {
        return ttpg;
    }

    /**
     * Sets the value of the ttpg property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTtpg(String value) {
        this.ttpg = value;
    }

    /**
     * Gets the value of the pepeid property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getPepeid() {
        return pepeid;
    }

    /**
     * Sets the value of the pepeid property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setPepeid(String value) {
        this.pepeid = value;
    }

}
