
name: build pull request

on:
  pull_request:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
       MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Build with Maven
      run: mvn -B clean test
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: ${{ success() || failure()}}

