---
name: build pull request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    if: ${{ !startsWith(GITHUB_HEAD_REF, 'feature/')}}
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.10.0
        continue-on-error: true # for act
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 8
      - name: Build with Maven
        run: |
          mvn -B -P"npm" -U -fae deploy
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.0.0
        if: (success() || failure())
        with:
          junit_files: "**/target/surefire-reports/*.xml"
