---
name: build pull request
run-name: build pull request ${{  github.ref_name }}

# Builds a pull request, basing the artifact name on the branch name on which it is based, so it can be published
# without breaking things, and enabled to build other pull requests depending on the current one.

# For e.g. if you make a pull request based on a branch feature/foobar on the main branch which is 6.1-SNAPSHOT,
# then it will be built and published as 6.1.foobar-SNAPSHOT
on:
  pull_request:
    branches: [main, REL-*]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    steps:
      - name: Cancel previous Action
        uses: styfle/cancel-workflow-action@0.12.1
        continue-on-error: true # for act
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
      - name: Build with Maven
        run: |
          mvn -B -Dchangelist=.${GITHUB_HEAD_REF##*/}-SNAPSHOT -P"npm" -U -fae deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME}}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD}}
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.20.0
        if: (success() || failure())
        with:
          junit_files: "**/target/surefire-reports/*.xml"
