
name: build pull request

on:
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
       MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean package

