
name: build pull request

on:
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest
    env:
       MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Clean settings.xml
      run: rm -rf ~/.m2/settings.xml
    - name: Create settings.xml
      uses: s4u/maven-settings-action@v1
      with:
        servers: '[{"id": "vpro-ossrh", "username": "vpro", "password": "${{secrets.SONATYPE_PASSWORD}}"}]'
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml  -Dgpg.skip=true
    - name: Publish Test Report
      uses: scacap/action-surefire-report@v1
      if: always()
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

