---
name: release
run-name: Creating release by ${{ github.actor }} on ${{ github.ref_name }}
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: '--no-transfer-progress'
    if: startsWith(github.ref, 'refs/heads/REL-')
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          global: true
          name: 'github $GITHUB_ACTOR'
          email: 'github@mmprogrami.nl'
          token: '${{ secrets.GITHUB_TOKEN  }}'
      - name: Release
        run: |
          mvn -U --batch-mode  -Darguments=-DskipTests  -DpushChanges=false release:prepare
          git push --atomic -v --follow-tags
          mvn -Pdeploy,central --batch-mode -Darguments=-DskipTests release:perform
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
