name: release
on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    if: startsWith(github.ref, 'refs/heads/REL-')
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    - name: Create settings.xml
      uses: s4u/maven-settings-action@v2
      with:
        servers: '[{"id": "vpro-ossrh", "username": "vpro", "password": "${{secrets.SONATYPE_PASSWORD}}"}]'
    - uses: crazy-max/ghaction-import-gpg@v3
      with:
        gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
        passphrase: ${{ secrets.GPG_SECRET_KEY_PASSPHRASE }}
    - uses: oleksiyrudenko/gha-git-credentials@v2.1
      with:
        global: true
        name: 'github $GITHUB_ACTOR'
        email: 'digitaal-techniek@vpro.nl'
        token: '${{ secrets.GITHUB_TOKEN  }}'
    - name: Release
      run: |
        mvn --batch-mode  -Darguments=-DskipTests  -DpushChanges=false release:prepare
        git push--atomic -v --follow-tags
        mvn --batch-mode -Darguments=-DskipTests release:perform


